intro_boss_defeated = "Intro Boss Defeated"
intro_clear = "Intro Stage Completed"
intro_hp_1 = "Intro Stage Life Energy (1)"
intro_hp_2 = "Intro Stage Max Life Energy (1)"
intro_1up = "Intro Stage 1 Up (1)"

web_spider_capsule = "Legs Upgrade"
web_spider_heart_tank = "Web Spider Heart Tank"
web_spider_defeated = "Web Spider Defeated"
web_spider_weapon = "Web Spider Weapon"
web_spider_hp_1 = "Web Spider Life Energy (1)"
web_spider_hp_2 = "Web Spider Max Life Energy (1)"

cyber_peacock_heart_tank = "Cyber Peacock Heart Tank"
cyber_peacock_sub_tank = "Cyber Peacock Sub Tank"
cyber_peacock_capsule = "Helmet Upgrade"
cyber_peacock_defeated = "Cyber Peacock Defeated"
cyber_peacock_weapon = "Cyber Peacock Weapon"

storm_owl_heart_tank = "Storm Owl Heart Tank"
storm_owl_capsule_1 = "Arms Upgrade 1"
storm_owl_capsule_2 = "Arms Upgrade 2"
storm_owl_defeated = "Storm Owl Defeated"
storm_owl_weapon = "Storm Owl Weapon"
storm_owl_hp_1 = "Storm Owl Life Energy (1)"
storm_owl_hp_2 = "Storm Owl Max Life Energy (1)"

magma_dragoon_heart_tank = "Magma Dragoon Heart Tank"
magma_dragoon_capsule = "Body Upgrade"
magma_dragoon_defeated = "Magma Dragoon Defeated"
magma_dragoon_weapon = "Magma Dragoon Weapon"
magma_dragoon_hp_1 = "Magma Dragoon Life Energy (1)"
magma_dragoon_hp_2 = "Magma Dragoon Life Energy (2)"
magma_dragoon_hp_3 = "Magma Dragoon Life Energy (3)"

jet_stingray_heart_tank = "Jet Stingray Heart Tank"
jet_stingray_sub_tank = "Jet Stingray Sub Tank"
jet_stingray_defeated = "Jet Stingray Defeated"
jet_stingray_weapon = "Jet Stingray Weapon"
jet_stingray_hp_1 = "Jet Stingray Max Life Energy (1)"

split_mushroom_heart_tank = "Split Mushroom Heart Tank"
split_mushroom_defeated = "Split Mushroom Defeated"
split_mushroom_weapon = "Split Mushroom Weapon"
split_mushroom_hp_1 = "Split Mushroom Life Energy (1)"
split_mushroom_wpn_1 = "Split Mushroom Weapon Energy (1)"

slash_beast_heart_tank = "Slash Beast Heart Tank"
slash_beast_defeated = "Slash Beast Defeated"
slash_beast_weapon = "Slash Beast Weapon"
slash_beast_hp_1 = "Slash Beast Max Life Energy (1)"

frost_walrus_heart_tank = "Frost Walrus Heart Tank"
frost_walrus_extra_lives_tank = "Frost Walrus Extra Lives Tank"
frost_walrus_weapon_tank = "Frost Walrus Weapon Tank"
frost_walrus_defeated = "Frost Walrus Defeated"
frost_walrus_weapon = "Frost Walrus Weapon"
frost_walrus_wpn_1 = "Frost Walrus Weapon Energy (1)"
frost_walrus_wpn_2 = "Frost Walrus Weapon Energy (2)"
frost_walrus_hp_1 = "Frost Walrus Life Energy (1)"
frost_walrus_hp_2 = "Frost Walrus Life Energy (2)"
frost_walrus_1up_1 = "Frost Walrus 1 Up (1)"
frost_walrus_hp_3 = "Frost Walrus Life Energy (3)"
frost_walrus_hp_4 = "Frost Walrus Life Energy (4)"
frost_walrus_hp_5 = "Frost Walrus Life Energy (5)"
frost_walrus_hp_6 = "Frost Walrus Life Energy (6)"
frost_walrus_hp_7 = "Frost Walrus Life Energy (7)"
frost_walrus_hp_8 = "Frost Walrus Life Energy (8)"
frost_walrus_1up_2 = "Frost Walrus 1 Up (2)"
frost_walrus_hp_9 = "Frost Walrus Max Life Energy (1)"
frost_walrus_wpn_3 = "Frost Walrus Max Weapon Energy (1)"

colonel_memorial_hall_defeated = "Memorial Hall Colonel Defeated"
colonel_space_port_defeated = "Space Port Colonel Defeated"
double_iris_defeated = "Double / Iris Defeated"
general_defeated = "General Defeated"

rematch_web_spider = "Web Spider Defeated (Rematch)"
rematch_cyber_peacock = "Cyber Peacock Defeated (Rematch)"
rematch_storm_owl = "Storm Owl Defeated (Rematch)"
rematch_magma_dragoon = "Magma Dragoon Defeated (Rematch)"
rematch_jet_stingray = "Jet Stingray Defeated (Rematch)"
rematch_split_mushroom = "Split Mushroom Defeated (Rematch)"
rematch_slash_beast = "Slash Beast Defeated (Rematch)"
rematch_frost_walrus = "Frost Walrus Defeated (Rematch)"

final_weapon_hp_1 = "Final Weapon Life Energy (1)"
final_weapon_hp_2 = "Final Weapon Max Life Energy (1)"
final_weapon_hp_3 = "Final Weapon Max Life Energy (2)"
final_weapon_hp_4 = "Final Weapon Max Life Energy (3)"
final_weapon_hp_5 = "Final Weapon Life Energy (2)"
final_weapon_hp_6 = "Final Weapon Life Energy (Boss Rush)"
final_weapon_wpn_1 = "Final Weapon Weapon Energy (Boss Rush)"
final_weapon_hp_7 = "Final Weapon Max Life Energy (4)"
final_weapon_wpn_2 = "Final Weapon Max Weapon Energy (1)"
final_weapon_hp_8 = "Final Weapon Life Energy (3)"

final_weapon_clear = "Sigma Defeated"
