k_rool = "Recovered Banana Hoard"
jungle_level = "Cleared Kongo Jungle Level"
mines_level = "Cleared Monkey Mines Level"
valley_level = "Cleared Vine Valley Level"
glacier_level = "Cleared Gorilla Glacier Level"
industries_level = "Cleared Kremkroc Industries Level"
caverns_level = "Cleared Chimp Caverns Level"

jungle_hijinxs_clear = "Jungle Hijinxs - Clear (Map Event)"
ropey_rampage_clear = "Ropey Rampage - Clear (Map Event)"
reptile_rumble_clear = "Reptile Rumble - Clear (Map Event)"
coral_capers_clear = "Coral Capers - Clear (Map Event)"
barrel_cannon_canyon_clear = "Barrel Cannon Canyon - Clear (Map Event)"

winky_walkway_clear = "Winky's Walkway - Clear (Map Event)"
mine_cart_carnage_clear = "Mine Cart Carnage - Clear (Map Event)"
bouncy_bonanza_clear = "Bouncy Bonanza - Clear (Map Event)"
stop_go_station_clear = "Stop & Go Station - Clear (Map Event)"
millstone_mayhem_clear = "Millstone Mayhem - Clear (Map Event)"

vulture_culture_clear = "Vulture Culture - Clear (Map Event)"
tree_top_town_clear = "Tree Top Town - Clear (Map Event)"
forest_frenzy_clear = "Forest Frenzy - Clear (Map Event)"
temple_tempest_clear = "Temple Tempest - Clear (Map Event)"
orang_utan_gang_clear = "Orang-utan Gang - Clear (Map Event)"
clam_city_clear = "Clam City - Clear (Map Event)"

snow_barrel_blast_clear = "Snow Barrel Blast - Clear (Map Event)"
slipslide_ride_clear = "Slipslide Ride - Clear (Map Event)"
ice_age_alley_clear = "Ice Age Alley - Clear (Map Event)"
croctopus_chase_clear = "Croctopus Chase - Clear (Map Event)"
torchlight_trouble_clear = "Torchlight Trouble - Clear (Map Event)"
rope_bridge_rumble_clear = "Rope Bridge Rumble - Clear (Map Event)"

oil_drum_alley_clear = "Oil Drum Alley - Clear (Map Event)"
trick_track_trek_clear = "Trick Track Trek - Clear (Map Event)"
elevator_antics_clear = "Elevator Antics - Clear (Map Event)"
poison_pond_clear = "Poison Pond - Clear (Map Event)"
mine_cart_madness_clear = "Mine Cart Madness - Clear (Map Event)"
blackout_basement_clear = "Blackout Basement - Clear (Map Event)"

tanked_up_trouble_clear = "Tanked Up Trouble - Clear (Map Event)"
manic_mincers_clear = "Manic Mincers - Clear (Map Event)"
misty_mine_clear = "Misty Mine - Clear (Map Event)"
loopy_lights_clear = "Loopy Lights - Clear (Map Event)"
platform_perils_clear = "Platform Perils - Clear (Map Event)"
