falcon_2 = "Falcon 2"
falcon_2_silencer = "Falcon 2 (Silencer)"
falcon_2_scope = "Falcon 2 (Scope)"
magsec_4 = "MagSec 4"
mauler = "Mauler"
phoenix = "Phoenix"
dy357_magnum = "DY357 Magnum"
dy357_lx = "DY357-LX"
cmp150 = "CMP150"
cyclone = "Cyclone"
callisto_ntg = "Callisto NTG"
rc_p120 = "RC-P120"
laptop_gun = "Laptop Gun"
dragon = "Dragon"
k7_avenger = "K7 Avenger"
ar34 = "AR34"
superdragon = "SuperDragon"
shotgun = "Shotgun"
reaper = "Reaper"
sniper_rifle = "Sniper Rifle"
farsight_xr_20 = "FarSight XR-20"
devastator = "Devastator"
rocket_launcher = "Rocket Launcher"
slayer = "Slayer"
combat_knife = "Combat Knife"
crossbow = "Crossbow"
tranquilizer = "Tranquilizer"
laser = "Laser"
grenade = "Grenade"
timed_mine = "Timed Mine"
proximity_mine = "Proximity Mine"
remote_mine = "Remote Mine"
psychosis_gun = "Psychosis Gun"
pp9i = "PP9i"
cci3 = "CCI3"
klo1313 = "KLO1313"
kf7_special = "KF7 Special"
zzt_9mm = "ZZT (9mm)"
dmc = "DMC"
ar53 = "AR53"
rc_p45 = "RC-P45"
n_bomb = "N-Bomb"

# Gadgets
data_uplink = "Data Uplink"
ecm_mine = "ECM Mine"
cam_spy = "CamSpy"
drug_spy = "DrugSpy"
bomb_spy = "BombSpy"
night_vision = "Night Vision"
door_decoder = "Door Decoder"
r_tracker = "R-Tracker"
ir_scanner = "IR Scanner"
x_ray_scanner = "X-Ray Scanner"
horizon_scanner = "Horizon Scanner"
cloaking_device = "Cloaking Device"
combat_boost = "Combat Boost"
disguise = "Disguise"

# QoL
shields = "Progressive Shields"
health = "Extra Health"
secondary_action = "Weapons Secondary Action"
akimbo_weapons = "Akimbo Wepaons"
hurricane_fists = "Hurricane Fists"
start_slots = "Starting Weapon Slot"
starting_ammo = "Starting Extra Ammo"

# Missions
mission_1 = "Mission 1"
mission_2 = "Mission 2"
mission_3 = "Mission 3"
mission_4 = "Mission 4"
mission_5 = "Mission 5"
mission_6 = "Mission 6"
mission_7 = "Mission 7"
mission_8 = "Mission 8"
mission_9 = "Mission 9"
special_assignments = "Special Assignments"

# Filler
pistol_ammo = "Box of pistol bullets"
magnum_ammo = "Box of magnum bullets"
smg_ammo = "Box of SMG bullets"
rifle_ammo = "Box of rifle bullets"
shotgun_ammo = "Box of shotgun shells"
bolt_ammo = "Box of bolts"
farsight_ammo = "Box of orbs"
grenade_ammo = "A grenade round"
rocket_ammo = "A rocket"
sedative_ammo = "Box of sedatives"
n_bomb_ammo = "A N-Bomb"
hp_refill = "Medkit"

# Events
medal = "Assignment Medal"
victory = "Defeated Skedar Leader"