from BaseClasses import Location
from .enums import Locations
from .constants import *

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from . import DKC3World

class DKC3Location(Location):
    game = GAME_NAME
    def __init__(self, player: int, name: str = '', address: int = None, parent=None):
        super().__init__(player, str(name), address, parent)

stage_clears = {
    Locations.lakeside_limbo_clear:         CLEAR | L11 | 0x02,
    Locations.doorstop_dash_clear:          CLEAR | L12 | 0x02,
    Locations.tidal_trouble_clear:          CLEAR | L13 | 0x02,
    Locations.skiddas_row_clear:            CLEAR | L14 | 0x02,
    Locations.murky_mill_clear:             CLEAR | L15 | 0x02,
    Locations.barrel_shield_bust_up_clear:  CLEAR | L21 | 0x02,
    Locations.riverside_race_clear:         CLEAR | L22 | 0x02,
    Locations.squeals_on_wheels_clear:      CLEAR | L23 | 0x02,
    Locations.springing_spiders_clear:      CLEAR | L24 | 0x02,
    Locations.bobbing_barrel_brawl_clear:   CLEAR | L25 | 0x02,
    Locations.bazzas_blockade_clear:        CLEAR | L31 | 0x02,
    Locations.rocket_barrel_ride_clear:     CLEAR | L32 | 0x02,
    Locations.kreeping_klasps_clear:        CLEAR | L33 | 0x02,
    Locations.tracker_barrel_trek_clear:    CLEAR | L34 | 0x02,
    Locations.fish_food_frenzy_clear:       CLEAR | L35 | 0x02,
    Locations.fireball_frenzy_clear:        CLEAR | L41 | 0x02,
    Locations.demolition_drain_pipe_clear:  CLEAR | L42 | 0x02,
    Locations.ripsaw_rage_clear:            CLEAR | L43 | 0x02,
    Locations.blazing_bazukas_clear:        CLEAR | L44 | 0x02,
    Locations.low_g_labyrinth_clear:        CLEAR | L45 | 0x02,
    Locations.krevice_kreepers_clear:       CLEAR | L51 | 0x02,
    Locations.tearaway_toboggan_clear:      CLEAR | L52 | 0x02,
    Locations.barrel_drop_bounce_clear:     CLEAR | L53 | 0x02,
    Locations.krackshot_krock_clear:        CLEAR | L54 | 0x02,
    Locations.lemguin_lunge_clear:          CLEAR | L55 | 0x02,
    Locations.buzzer_barrage_clear:         CLEAR | L61 | 0x02,
    Locations.kongfused_cliffs_clear:       CLEAR | L62 | 0x02,
    Locations.floodlit_fish_clear:          CLEAR | L63 | 0x02,
    Locations.pot_hole_panic_clear:         CLEAR | L64 | 0x02,
    Locations.ropey_rumpus_clear:           CLEAR | L65 | 0x02,
    Locations.konveyor_rope_klash_clear:    CLEAR | L71 | 0x02,
    Locations.creepy_caverns_clear:         CLEAR | L72 | 0x02,
    Locations.lightning_look_out_clear:     CLEAR | L73 | 0x02,
    Locations.koindozer_klamber_clear:      CLEAR | L74 | 0x02,
    Locations.poisonous_pipeline_clear:     CLEAR | L75 | 0x02,
    Locations.stampede_sprint_clear:        CLEAR | L81 | 0x02,
    Locations.criss_kross_cliffs_clear:     CLEAR | L82 | 0x02,
    Locations.tyrant_twin_tussle_clear:     CLEAR | L83 | 0x02,
    Locations.swoopy_salvo_clear:           CLEAR | L84 | 0x02,
    Locations.rocket_rush_clear:            CLEAR | L85 | 0x02,

    Locations.belchas_barn_clear:           CLEAR | L1B | 0x02,
    Locations.arichs_ambush_clear:          CLEAR | L2B | 0x02,
    Locations.squirt_showdown_clear:        CLEAR | L3B | 0x02,
    Locations.kaos_karnage_clear:           CLEAR | L4B | 0x02,
    Locations.bleaks_house_clear:           CLEAR | L5B | 0x02,
    Locations.barbos_barrier_clear:         CLEAR | L6B | 0x02,

    Locations.defeated_belcha:              BOSS | L1B | 0x02,
    Locations.defeated_arich:               BOSS | L2B | 0x02,
    Locations.defeated_squirt:              BOSS | L3B | 0x02,
    Locations.defeated_kaos:                BOSS | L4B | 0x02,
    Locations.defeated_bleak:               BOSS | L5B | 0x02,
    Locations.defeated_barbos:              BOSS | L6B | 0x02,
}

stage_kong = {
    Locations.lakeside_limbo_kong:         KONG | L11 | 0x80,
    Locations.doorstop_dash_kong:          KONG | L12 | 0x80,
    Locations.tidal_trouble_kong:          KONG | L13 | 0x80,
    Locations.skiddas_row_kong:            KONG | L14 | 0x80,
    Locations.murky_mill_kong:             KONG | L15 | 0x80,
    Locations.barrel_shield_bust_up_kong:  KONG | L21 | 0x80,
    Locations.riverside_race_kong:         KONG | L22 | 0x80,
    Locations.squeals_on_wheels_kong:      KONG | L23 | 0x80,
    Locations.springing_spiders_kong:      KONG | L24 | 0x80,
    Locations.bobbing_barrel_brawl_kong:   KONG | L25 | 0x80,
    Locations.bazzas_blockade_kong:        KONG | L31 | 0x80,
    Locations.rocket_barrel_ride_kong:     KONG | L32 | 0x80,
    Locations.kreeping_klasps_kong:        KONG | L33 | 0x80,
    Locations.tracker_barrel_trek_kong:    KONG | L34 | 0x80,
    Locations.fish_food_frenzy_kong:       KONG | L35 | 0x80,
    Locations.fireball_frenzy_kong:        KONG | L41 | 0x80,
    Locations.demolition_drain_pipe_kong:  KONG | L42 | 0x80,
    Locations.ripsaw_rage_kong:            KONG | L43 | 0x80,
    Locations.blazing_bazukas_kong:        KONG | L44 | 0x80,
    Locations.low_g_labyrinth_kong:        KONG | L45 | 0x80,
    Locations.krevice_kreepers_kong:       KONG | L51 | 0x80,
    Locations.tearaway_toboggan_kong:      KONG | L52 | 0x80,
    Locations.barrel_drop_bounce_kong:     KONG | L53 | 0x80,
    Locations.krackshot_krock_kong:        KONG | L54 | 0x80,
    Locations.lemguin_lunge_kong:          KONG | L55 | 0x80,
    Locations.buzzer_barrage_kong:         KONG | L61 | 0x80,
    Locations.kongfused_cliffs_kong:       KONG | L62 | 0x80,
    Locations.floodlit_fish_kong:          KONG | L63 | 0x80,
    Locations.pot_hole_panic_kong:         KONG | L64 | 0x80,
    Locations.ropey_rumpus_kong:           KONG | L65 | 0x80,
    Locations.konveyor_rope_klash_kong:    KONG | L71 | 0x80,
    Locations.creepy_caverns_kong:         KONG | L72 | 0x80,
    Locations.lightning_look_out_kong:     KONG | L73 | 0x80,
    Locations.koindozer_klamber_kong:      KONG | L74 | 0x80,
    Locations.poisonous_pipeline_kong:     KONG | L75 | 0x80,
    Locations.stampede_sprint_kong:        KONG | L81 | 0x80,
    Locations.criss_kross_cliffs_kong:     KONG | L82 | 0x80,
    Locations.tyrant_twin_tussle_kong:     KONG | L83 | 0x80,
    Locations.swoopy_salvo_kong:           KONG | L84 | 0x80,
}

stage_bonus = {
    Locations.lakeside_limbo_bonus_1:         BONUS | L11 | 0x04,
    Locations.lakeside_limbo_bonus_2:         BONUS | L11 | 0x08,
    Locations.doorstop_dash_bonus_1:          BONUS | L12 | 0x04,
    Locations.doorstop_dash_bonus_2:          BONUS | L12 | 0x08,
    Locations.tidal_trouble_bonus_1:          BONUS | L13 | 0x04,
    Locations.tidal_trouble_bonus_2:          BONUS | L13 | 0x08,
    Locations.skiddas_row_bonus_1:            BONUS | L14 | 0x04,
    Locations.skiddas_row_bonus_2:            BONUS | L14 | 0x08,
    Locations.murky_mill_bonus_1:             BONUS | L15 | 0x04,
    Locations.murky_mill_bonus_2:             BONUS | L15 | 0x08,
    Locations.barrel_shield_bust_up_bonus_1:  BONUS | L21 | 0x04,
    Locations.barrel_shield_bust_up_bonus_2:  BONUS | L21 | 0x08,
    Locations.riverside_race_bonus_1:         BONUS | L22 | 0x04,
    Locations.riverside_race_bonus_2:         BONUS | L22 | 0x08,
    Locations.squeals_on_wheels_bonus_1:      BONUS | L23 | 0x04,
    Locations.squeals_on_wheels_bonus_2:      BONUS | L23 | 0x08,
    Locations.springing_spiders_bonus_1:      BONUS | L24 | 0x04,
    Locations.springing_spiders_bonus_2:      BONUS | L24 | 0x08,
    Locations.bobbing_barrel_brawl_bonus_1:   BONUS | L25 | 0x04,
    Locations.bobbing_barrel_brawl_bonus_2:   BONUS | L25 | 0x08,
    Locations.bazzas_blockade_bonus_1:        BONUS | L31 | 0x04,
    Locations.bazzas_blockade_bonus_2:        BONUS | L31 | 0x08,
    Locations.rocket_barrel_ride_bonus_1:     BONUS | L32 | 0x04,
    Locations.rocket_barrel_ride_bonus_2:     BONUS | L32 | 0x08,
    Locations.kreeping_klasps_bonus_1:        BONUS | L33 | 0x04,
    Locations.kreeping_klasps_bonus_2:        BONUS | L33 | 0x08,
    Locations.tracker_barrel_trek_bonus_1:    BONUS | L34 | 0x04,
    Locations.tracker_barrel_trek_bonus_2:    BONUS | L34 | 0x08,
    Locations.fish_food_frenzy_bonus_1:       BONUS | L35 | 0x04,
    Locations.fish_food_frenzy_bonus_2:       BONUS | L35 | 0x08,
    Locations.fireball_frenzy_bonus_1:        BONUS | L41 | 0x04,
    Locations.fireball_frenzy_bonus_2:        BONUS | L41 | 0x08,
    Locations.demolition_drain_pipe_bonus_1:  BONUS | L42 | 0x04,
    Locations.demolition_drain_pipe_bonus_2:  BONUS | L42 | 0x08,
    Locations.ripsaw_rage_bonus_1:            BONUS | L43 | 0x04,
    Locations.ripsaw_rage_bonus_2:            BONUS | L43 | 0x08,
    Locations.blazing_bazukas_bonus_1:        BONUS | L44 | 0x04,
    Locations.blazing_bazukas_bonus_2:        BONUS | L44 | 0x08,
    Locations.low_g_labyrinth_bonus_1:        BONUS | L45 | 0x04,
    Locations.low_g_labyrinth_bonus_2:        BONUS | L45 | 0x08,
    Locations.krevice_kreepers_bonus_1:       BONUS | L51 | 0x04,
    Locations.krevice_kreepers_bonus_2:       BONUS | L51 | 0x08,
    Locations.tearaway_toboggan_bonus_1:      BONUS | L52 | 0x04,
    Locations.tearaway_toboggan_bonus_2:      BONUS | L52 | 0x08,
    Locations.barrel_drop_bounce_bonus_1:     BONUS | L53 | 0x04,
    Locations.barrel_drop_bounce_bonus_2:     BONUS | L53 | 0x08,
    Locations.krackshot_krock_bonus_1:        BONUS | L54 | 0x04,
    Locations.krackshot_krock_bonus_2:        BONUS | L54 | 0x08,
    Locations.lemguin_lunge_bonus_1:          BONUS | L55 | 0x04,
    Locations.lemguin_lunge_bonus_2:          BONUS | L55 | 0x08,
    Locations.buzzer_barrage_bonus_1:         BONUS | L61 | 0x04,
    Locations.buzzer_barrage_bonus_2:         BONUS | L61 | 0x08,
    Locations.kongfused_cliffs_bonus_1:       BONUS | L62 | 0x04,
    Locations.kongfused_cliffs_bonus_2:       BONUS | L62 | 0x08,
    Locations.floodlit_fish_bonus_1:          BONUS | L63 | 0x04,
    Locations.floodlit_fish_bonus_2:          BONUS | L63 | 0x08,
    Locations.pot_hole_panic_bonus_1:         BONUS | L64 | 0x04,
    Locations.pot_hole_panic_bonus_2:         BONUS | L64 | 0x08,
    Locations.ropey_rumpus_bonus_1:           BONUS | L65 | 0x04,
    Locations.ropey_rumpus_bonus_2:           BONUS | L65 | 0x08,
    Locations.konveyor_rope_klash_bonus_1:    BONUS | L71 | 0x04,
    Locations.konveyor_rope_klash_bonus_2:    BONUS | L71 | 0x08,
    Locations.creepy_caverns_bonus_1:         BONUS | L72 | 0x04,
    Locations.creepy_caverns_bonus_2:         BONUS | L72 | 0x08,
    Locations.lightning_look_out_bonus_1:     BONUS | L73 | 0x04,
    Locations.lightning_look_out_bonus_2:     BONUS | L73 | 0x08,
    Locations.koindozer_klamber_bonus_1:      BONUS | L74 | 0x04,
    Locations.koindozer_klamber_bonus_2:      BONUS | L74 | 0x08,
    Locations.poisonous_pipeline_bonus_1:     BONUS | L75 | 0x04,
    Locations.poisonous_pipeline_bonus_2:     BONUS | L75 | 0x08,
    Locations.stampede_sprint_bonus_1:        BONUS | L81 | 0x04,
    Locations.stampede_sprint_bonus_2:        BONUS | L81 | 0x10,
    Locations.stampede_sprint_bonus_3:        BONUS | L81 | 0x08,
    Locations.criss_kross_cliffs_bonus_1:     BONUS | L82 | 0x04,
    Locations.criss_kross_cliffs_bonus_2:     BONUS | L82 | 0x08,
    Locations.tyrant_twin_tussle_bonus_1:     BONUS | L83 | 0x04,
    Locations.tyrant_twin_tussle_bonus_2:     BONUS | L83 | 0x08,
    Locations.tyrant_twin_tussle_bonus_3:     BONUS | L83 | 0x10,
    Locations.swoopy_salvo_bonus_1:           BONUS | L84 | 0x04,
    Locations.swoopy_salvo_bonus_2:           BONUS | L84 | 0x08,
    Locations.swoopy_salvo_bonus_3:           BONUS | L84 | 0x10,
}

stage_dk_coins = {
    Locations.lakeside_limbo_dk_coin:         DKCOIN | L11 | 0x20,
    Locations.doorstop_dash_dk_coin:          DKCOIN | L12 | 0x20,
    Locations.tidal_trouble_dk_coin:          DKCOIN | L13 | 0x20,
    Locations.skiddas_row_dk_coin:            DKCOIN | L14 | 0x20,
    Locations.murky_mill_dk_coin:             DKCOIN | L15 | 0x20,
    Locations.barrel_shield_bust_up_dk_coin:  DKCOIN | L21 | 0x20,
    Locations.riverside_race_dk_coin:         DKCOIN | L22 | 0x20,
    Locations.squeals_on_wheels_dk_coin:      DKCOIN | L23 | 0x20,
    Locations.springing_spiders_dk_coin:      DKCOIN | L24 | 0x20,
    Locations.bobbing_barrel_brawl_dk_coin:   DKCOIN | L25 | 0x20,
    Locations.bazzas_blockade_dk_coin:        DKCOIN | L31 | 0x20,
    Locations.rocket_barrel_ride_dk_coin:     DKCOIN | L32 | 0x20,
    Locations.kreeping_klasps_dk_coin:        DKCOIN | L33 | 0x20,
    Locations.tracker_barrel_trek_dk_coin:    DKCOIN | L34 | 0x20,
    Locations.fish_food_frenzy_dk_coin:       DKCOIN | L35 | 0x20,
    Locations.fireball_frenzy_dk_coin:        DKCOIN | L41 | 0x20,
    Locations.demolition_drain_pipe_dk_coin:  DKCOIN | L42 | 0x20,
    Locations.ripsaw_rage_dk_coin:            DKCOIN | L43 | 0x20,
    Locations.blazing_bazukas_dk_coin:        DKCOIN | L44 | 0x20,
    Locations.low_g_labyrinth_dk_coin:        DKCOIN | L45 | 0x20,
    Locations.krevice_kreepers_dk_coin:       DKCOIN | L51 | 0x20,
    Locations.tearaway_toboggan_dk_coin:      DKCOIN | L52 | 0x20,
    Locations.barrel_drop_bounce_dk_coin:     DKCOIN | L53 | 0x20,
    Locations.krackshot_krock_dk_coin:        DKCOIN | L54 | 0x20,
    Locations.lemguin_lunge_dk_coin:          DKCOIN | L55 | 0x20,
    Locations.buzzer_barrage_dk_coin:         DKCOIN | L61 | 0x20,
    Locations.kongfused_cliffs_dk_coin:       DKCOIN | L62 | 0x20,
    Locations.floodlit_fish_dk_coin:          DKCOIN | L63 | 0x20,
    Locations.pot_hole_panic_dk_coin:         DKCOIN | L64 | 0x20,
    Locations.ropey_rumpus_dk_coin:           DKCOIN | L65 | 0x20,
    Locations.konveyor_rope_klash_dk_coin:    DKCOIN | L71 | 0x20,
    Locations.creepy_caverns_dk_coin:         DKCOIN | L72 | 0x20,
    Locations.lightning_look_out_dk_coin:     DKCOIN | L73 | 0x20,
    Locations.koindozer_klamber_dk_coin:      DKCOIN | L74 | 0x20,
    Locations.poisonous_pipeline_dk_coin:     DKCOIN | L75 | 0x20,
    Locations.stampede_sprint_dk_coin:        DKCOIN | L81 | 0x20,
    Locations.criss_kross_cliffs_dk_coin:     DKCOIN | L82 | 0x20,
    Locations.tyrant_twin_tussle_dk_coin:     DKCOIN | L83 | 0x20,
    Locations.swoopy_salvo_dk_coin:           DKCOIN | L84 | 0x20,
    Locations.rocket_rush_dk_coin:            DKCOIN | L85 | 0x20,
}

stage_balloons = {
    Locations.lakeside_limbo_balloon_1:           BALLOON | L11 | 2,
    Locations.lakeside_limbo_balloon_2:           BALLOON | L11 | 3,
    Locations.lakeside_limbo_balloon_3:           BALLOON | L11 | 21,
    Locations.lakeside_limbo_balloon_4:           BALLOON | L11 | 31,
    Locations.lakeside_limbo_balloon_5:           BALLOON | L11 | 38,
    Locations.doorstop_dash_balloon_1:            BALLOON | L12 | 35,
    Locations.doorstop_dash_balloon_2:            BALLOON | L12 | 72,
    Locations.doorstop_dash_balloon_3:            BALLOON | L12 | 114,
    Locations.doorstop_dash_balloon_4:            BALLOON | L12 | 115,
    Locations.tidal_trouble_balloon_1:            BALLOON | L13 | 58,
    Locations.skiddas_row_balloon_1:              BALLOON | L14 | 33,
    Locations.murky_mill_balloon_1:               BALLOON | L15 | 24,
    Locations.riverside_race_balloon_1:           BALLOON | L22 | 24,
    Locations.squeals_on_wheels_balloon_1:        BALLOON | L23 | 139,
    Locations.springing_spiders_balloon_1:        BALLOON | L24 | 78,
    Locations.springing_spiders_balloon_2:        BALLOON | L24 | 62,
    Locations.springing_spiders_balloon_3:        BALLOON | L24 | 37,
    Locations.bobbing_barrel_brawl_balloon_1:     BALLOON | L25 | 0,
    Locations.rocket_barrel_ride_balloon_1:       BALLOON | L32 | 85,
    Locations.rocket_barrel_ride_balloon_2:       BALLOON | L32 | 89,
    Locations.kreeping_klasps_balloon_1:          BALLOON | L33 | 7,
    Locations.kreeping_klasps_balloon_2:          BALLOON | L33 | 23,
    Locations.tracker_barrel_trek_balloon_1:      BALLOON | L34 | 33,
    Locations.blazing_bazukas_balloon_1:          BALLOON | L44 | 111,
    Locations.low_g_labyrinth_balloon_1:          BALLOON | L45 | 91,
    Locations.krevice_kreepers_balloon_1:         BALLOON | L51 | 26,
    Locations.tearaway_toboggan_balloon_1:        BALLOON | L52 | 33,
    Locations.tearaway_toboggan_balloon_2:        BALLOON | L52 | 74,
    Locations.barrel_drop_bounce_balloon_1:       BALLOON | L53 | 41,
    Locations.krackshot_krock_balloon_1:          BALLOON | L54 | 79,
    Locations.buzzer_barrage_balloon_1:           BALLOON | L61 | 0,
    Locations.buzzer_barrage_balloon_2:           BALLOON | L61 | 124,
    Locations.buzzer_barrage_balloon_3:           BALLOON | L61 | 4,
    Locations.ropey_rumpus_balloon_1:             BALLOON | L65 | 71,
    Locations.ropey_rumpus_balloon_2:             BALLOON | L65 | 103,
    Locations.konveyor_rope_klash_balloon_1:      BALLOON | L71 | 69,
    Locations.konveyor_rope_klash_balloon_2:      BALLOON | L71 | 1,
    Locations.creepy_caverns_balloon_1:           BALLOON | L72 | 0,
    Locations.lightning_look_out_balloon_1:       BALLOON | L73 | 3,
    Locations.lightning_look_out_balloon_2:       BALLOON | L73 | 1,
    Locations.koindozer_klamber_balloon_1:        BALLOON | L74 | 1,
    Locations.poisonous_pipeline_balloon_1:       BALLOON | L75 | 71,
    Locations.criss_kross_cliffs_balloon_1:       BALLOON | L82 | 4,
    Locations.criss_kross_cliffs_balloon_2:       BALLOON | L82 | 1,
    Locations.tyrant_twin_tussle_balloon_1:       BALLOON | L83 | 17,
    Locations.tyrant_twin_tussle_balloon_2:       BALLOON | L83 | 0,
}

stage_bunches = {
    Locations.lakeside_limbo_bananas_1:           BANANAS | L11 | 4,
    Locations.lakeside_limbo_bananas_2:           BANANAS | L11 | 27,
    Locations.lakeside_limbo_bananas_3:           BANANAS | L11 | 45,
    Locations.lakeside_limbo_bananas_4:           BANANAS | L11 | 46,
    Locations.doorstop_dash_bananas_1:            BANANAS | L12 | 3,
    Locations.doorstop_dash_bananas_2:            BANANAS | L12 | 77,
    Locations.tidal_trouble_bananas_1:            BANANAS | L13 | 14,
    Locations.tidal_trouble_bananas_2:            BANANAS | L13 | 22,
    Locations.skiddas_row_bananas_1:              BANANAS | L14 | 32,
    Locations.murky_mill_bananas_1:               BANANAS | L15 | 10,
    Locations.murky_mill_bananas_2:               BANANAS | L15 | 13,
    Locations.barrel_shield_bust_up_bananas_1:    BANANAS | L21 | 7,
    Locations.barrel_shield_bust_up_bananas_2:    BANANAS | L21 | 30,
    Locations.riverside_race_bananas_1:           BANANAS | L22 | 2,
    Locations.riverside_race_bananas_2:           BANANAS | L22 | 15,
    Locations.riverside_race_bananas_3:           BANANAS | L22 | 32,
    Locations.riverside_race_bananas_4:           BANANAS | L22 | 33,
    Locations.riverside_race_bananas_5:           BANANAS | L22 | 35,
    Locations.riverside_race_bananas_6:           BANANAS | L22 | 52,
    Locations.squeals_on_wheels_bananas_1:        BANANAS | L23 | 45,
    Locations.squeals_on_wheels_bananas_2:        BANANAS | L23 | 51,
    Locations.squeals_on_wheels_bananas_3:        BANANAS | L23 | 53,
    Locations.squeals_on_wheels_bananas_4:        BANANAS | L23 | 104,
    Locations.squeals_on_wheels_bananas_5:        BANANAS | L23 | 105,
    Locations.squeals_on_wheels_bananas_6:        BANANAS | L23 | 113,
    Locations.squeals_on_wheels_bananas_7:        BANANAS | L23 | 121,
    Locations.springing_spiders_bananas_1:        BANANAS | L24 | 36,
    Locations.springing_spiders_bananas_2:        BANANAS | L24 | 68,
    Locations.springing_spiders_bananas_3:        BANANAS | L24 | 50,
    Locations.springing_spiders_bananas_4:        BANANAS | L24 | 101,
    Locations.springing_spiders_bananas_5:        BANANAS | L24 | 100,
    Locations.springing_spiders_bananas_6:        BANANAS | L24 | 109,
    Locations.bobbing_barrel_brawl_bananas_1:     BANANAS | L25 | 100,
    Locations.bazzas_blockade_bananas_1:          BANANAS | L31 | 14,
    Locations.bazzas_blockade_bananas_2:          BANANAS | L31 | 13,
    Locations.rocket_barrel_ride_bananas_1:       BANANAS | L32 | 5,
    Locations.rocket_barrel_ride_bananas_2:       BANANAS | L32 | 7,
    Locations.rocket_barrel_ride_bananas_3:       BANANAS | L32 | 16,
    Locations.rocket_barrel_ride_bananas_4:       BANANAS | L32 | 19,
    Locations.rocket_barrel_ride_bananas_5:       BANANAS | L32 | 49,
    Locations.rocket_barrel_ride_bananas_6:       BANANAS | L32 | 83,
    Locations.rocket_barrel_ride_bananas_7:       BANANAS | L32 | 84,
    Locations.kreeping_klasps_bananas_1:          BANANAS | L33 | 21,
    Locations.kreeping_klasps_bananas_2:          BANANAS | L33 | 29,
    Locations.tracker_barrel_trek_bananas_1:      BANANAS | L34 | 15,
    Locations.fish_food_frenzy_bananas_1:         BANANAS | L35 | 13,
    Locations.fireball_frenzy_bananas_1:          BANANAS | L41 | 49,
    Locations.fireball_frenzy_bananas_2:          BANANAS | L41 | 55,
    Locations.fireball_frenzy_bananas_3:          BANANAS | L41 | 72,
    Locations.demolition_drain_pipe_bananas_1:    BANANAS | L42 | 4,
    Locations.demolition_drain_pipe_bananas_2:    BANANAS | L42 | 15,
    Locations.demolition_drain_pipe_bananas_3:    BANANAS | L42 | 18,
    Locations.demolition_drain_pipe_bananas_4:    BANANAS | L42 | 36,
    Locations.demolition_drain_pipe_bananas_5:    BANANAS | L42 | 44,
    Locations.demolition_drain_pipe_bananas_6:    BANANAS | L42 | 63,
    Locations.demolition_drain_pipe_bananas_7:    BANANAS | L42 | 84,
    Locations.ripsaw_rage_bananas_1:              BANANAS | L43 | 7,
    Locations.ripsaw_rage_bananas_2:              BANANAS | L43 | 22,
    Locations.ripsaw_rage_bananas_3:              BANANAS | L43 | 31,
    Locations.ripsaw_rage_bananas_4:              BANANAS | L43 | 43,
    Locations.blazing_bazukas_bananas_1:          BANANAS | L44 | 45,
    Locations.blazing_bazukas_bananas_2:          BANANAS | L44 | 85,
    Locations.blazing_bazukas_bananas_3:          BANANAS | L44 | 101,
    Locations.low_g_labyrinth_bananas_1:          BANANAS | L45 | 8,
    Locations.low_g_labyrinth_bananas_2:          BANANAS | L45 | 31,
    Locations.low_g_labyrinth_bananas_3:          BANANAS | L45 | 79,
    Locations.low_g_labyrinth_bananas_4:          BANANAS | L45 | 116,
    Locations.krevice_kreepers_bananas_1:         BANANAS | L51 | 3,
    Locations.krevice_kreepers_bananas_2:         BANANAS | L51 | 4,
    Locations.krevice_kreepers_bananas_3:         BANANAS | L51 | 5,
    Locations.krevice_kreepers_bananas_4:         BANANAS | L51 | 13,
    Locations.tearaway_toboggan_bananas_1:        BANANAS | L52 | 15,
    Locations.tearaway_toboggan_bananas_2:        BANANAS | L52 | 27,
    Locations.tearaway_toboggan_bananas_3:        BANANAS | L52 | 31,
    Locations.tearaway_toboggan_bananas_4:        BANANAS | L52 | 46,
    Locations.tearaway_toboggan_bananas_5:        BANANAS | L52 | 66,
    Locations.tearaway_toboggan_bananas_6:        BANANAS | L52 | 67,
    Locations.tearaway_toboggan_bananas_7:        BANANAS | L52 | 71,
    Locations.krackshot_krock_bananas_1:          BANANAS | L54 | 72,
    Locations.krackshot_krock_bananas_2:          BANANAS | L54 | 57,
    Locations.krackshot_krock_bananas_3:          BANANAS | L54 | 19,
    Locations.krackshot_krock_bananas_4:          BANANAS | L54 | 35,
    Locations.krackshot_krock_bananas_5:          BANANAS | L54 | 38,
    Locations.lemguin_lunge_bananas_1:            BANANAS | L55 | 28,
    Locations.buzzer_barrage_bananas_1:           BANANAS | L61 | 21,
    Locations.buzzer_barrage_bananas_2:           BANANAS | L61 | 34,
    Locations.buzzer_barrage_bananas_3:           BANANAS | L61 | 29,
    Locations.buzzer_barrage_bananas_4:           BANANAS | L61 | 30,
    Locations.buzzer_barrage_bananas_5:           BANANAS | L61 | 52,
    Locations.buzzer_barrage_bananas_6:           BANANAS | L61 | 51,
    Locations.buzzer_barrage_bananas_7:           BANANAS | L61 | 75,
    Locations.kongfused_cliffs_bananas_1:         BANANAS | L62 | 7,
    Locations.kongfused_cliffs_bananas_2:         BANANAS | L62 | 5,
    Locations.floodlit_fish_bananas_1:            BANANAS | L63 | 0,
    Locations.floodlit_fish_bananas_2:            BANANAS | L63 | 43,
    Locations.floodlit_fish_bananas_3:            BANANAS | L63 | 59,
    Locations.floodlit_fish_bananas_4:            BANANAS | L63 | 58,
    Locations.floodlit_fish_bananas_5:            BANANAS | L63 | 77,
    Locations.floodlit_fish_bananas_6:            BANANAS | L63 | 94,
    Locations.floodlit_fish_bananas_7:            BANANAS | L63 | 105,
    Locations.floodlit_fish_bananas_8:            BANANAS | L63 | 106,
    Locations.pot_hole_panic_bananas_1:           BANANAS | L64 | 3,
    Locations.pot_hole_panic_bananas_2:           BANANAS | L64 | 4,
    Locations.pot_hole_panic_bananas_3:           BANANAS | L64 | 16,
    Locations.pot_hole_panic_bananas_4:           BANANAS | L64 | 26,
    Locations.pot_hole_panic_bananas_5:           BANANAS | L64 | 32,
    Locations.pot_hole_panic_bananas_6:           BANANAS | L64 | 34,
    Locations.pot_hole_panic_bananas_7:           BANANAS | L64 | 44,
    Locations.pot_hole_panic_bananas_8:           BANANAS | L64 | 43,
    Locations.pot_hole_panic_bananas_9:           BANANAS | L64 | 60,
    Locations.pot_hole_panic_bananas_10:          BANANAS | L64 | 71,
    Locations.pot_hole_panic_bananas_11:          BANANAS | L64 | 78,
    Locations.ropey_rumpus_bananas_1:             BANANAS | L65 | 6,
    Locations.ropey_rumpus_bananas_2:             BANANAS | L65 | 28,
    Locations.ropey_rumpus_bananas_3:             BANANAS | L65 | 45,
    Locations.ropey_rumpus_bananas_4:             BANANAS | L65 | 54,
    Locations.ropey_rumpus_bananas_5:             BANANAS | L65 | 73,
    Locations.ropey_rumpus_bananas_6:             BANANAS | L65 | 72,
    Locations.ropey_rumpus_bananas_7:             BANANAS | L65 | 91,
    Locations.ropey_rumpus_bananas_8:             BANANAS | L65 | 90,
    Locations.ropey_rumpus_bananas_9:             BANANAS | L65 | 102,
    Locations.ropey_rumpus_bananas_10:            BANANAS | L65 | 109,
    Locations.creepy_caverns_bananas_1:           BANANAS | L72 | 3,
    Locations.creepy_caverns_bananas_2:           BANANAS | L72 | 47,
    Locations.lightning_look_out_bananas_1:       BANANAS | L73 | 21,
    Locations.koindozer_klamber_bananas_1:        BANANAS | L74 | 33,
    Locations.poisonous_pipeline_bananas_1:       BANANAS | L75 | 18,
    Locations.poisonous_pipeline_bananas_2:       BANANAS | L75 | 17,
    Locations.criss_kross_cliffs_bananas_1:       BANANAS | L82 | 79,
    Locations.criss_kross_cliffs_bananas_2:       BANANAS | L82 | 49,
    Locations.criss_kross_cliffs_bananas_3:       BANANAS | L82 | 10,
    Locations.tyrant_twin_tussle_bananas_1:       BANANAS | L83 | 24,
    Locations.tyrant_twin_tussle_bananas_2:       BANANAS | L83 | 50,
    Locations.tyrant_twin_tussle_bananas_3:       BANANAS | L83 | 81,
    Locations.swoopy_salvo_bananas_1:             BANANAS | L84 | 84,
    Locations.swoopy_salvo_bananas_2:             BANANAS | L84 | 63,
    Locations.rocket_rush_bananas_1:              BANANAS | L85 | 6,
    Locations.rocket_rush_bananas_2:              BANANAS | L85 | 44,
    Locations.rocket_rush_bananas_3:              BANANAS | L85 | 45,
}

stage_coins = {
    Locations.lakeside_limbo_coin_1:              COIN | L11 | 20,
    Locations.lakeside_limbo_coin_2:              COIN | L11 | 22,
    Locations.lakeside_limbo_coin_3:              COIN | L11 | 41,
    Locations.lakeside_limbo_coin_4:              COIN | L11 | 44,
    Locations.doorstop_dash_coin_1:               COIN | L12 | 18,
    Locations.doorstop_dash_coin_2:               COIN | L12 | 78,
    Locations.tidal_trouble_coin_1:               COIN | L13 | 29,
    Locations.tidal_trouble_coin_2:               COIN | L13 | 32,
    Locations.skiddas_row_coin_1:                 COIN | L14 | 6,
    Locations.skiddas_row_coin_2:                 COIN | L14 | 9,
    Locations.skiddas_row_coin_3:                 COIN | L14 | 16,
    Locations.murky_mill_coin_1:                  COIN | L15 | 18,
    Locations.murky_mill_coin_2:                  COIN | L15 | 52,
    Locations.murky_mill_coin_3:                  COIN | L15 | 77,
    Locations.barrel_shield_bust_up_coin_1:       COIN | L21 | 34,
    Locations.barrel_shield_bust_up_coin_2:       COIN | L21 | 60,
    Locations.riverside_race_coin_1:              COIN | L22 | 8,
    Locations.riverside_race_coin_2:              COIN | L22 | 10,
    Locations.riverside_race_coin_3:              COIN | L22 | 49,
    Locations.riverside_race_coin_4:              COIN | L22 | 60,
    Locations.squeals_on_wheels_coin_1:           COIN | L23 | 135,
    Locations.springing_spiders_coin_1:           COIN | L24 | 63,
    Locations.springing_spiders_coin_2:           COIN | L24 | 77,
    Locations.springing_spiders_coin_3:           COIN | L24 | 76,
    Locations.springing_spiders_coin_4:           COIN | L24 | 120,
    Locations.springing_spiders_coin_5:           COIN | L24 | 88,
    Locations.springing_spiders_coin_6:           COIN | L24 | 47,
    Locations.springing_spiders_coin_7:           COIN | L24 | 72,
    Locations.bobbing_barrel_brawl_coin_1:        COIN | L25 | 40,
    Locations.bobbing_barrel_brawl_coin_2:        COIN | L25 | 90,
    Locations.bobbing_barrel_brawl_coin_3:        COIN | L25 | 1,
    Locations.bazzas_blockade_coin_1:             COIN | L31 | 38,
    Locations.bazzas_blockade_coin_2:             COIN | L31 | 37,
    Locations.bazzas_blockade_coin_3:             COIN | L31 | 62,
    Locations.bazzas_blockade_coin_4:             COIN | L31 | 87,
    Locations.rocket_barrel_ride_coin_1:          COIN | L32 | 8,
    Locations.rocket_barrel_ride_coin_2:          COIN | L32 | 11,
    Locations.rocket_barrel_ride_coin_3:          COIN | L32 | 17,
    Locations.rocket_barrel_ride_coin_4:          COIN | L32 | 25,
    Locations.rocket_barrel_ride_coin_5:          COIN | L32 | 36,
    Locations.rocket_barrel_ride_coin_6:          COIN | L32 | 58,
    Locations.kreeping_klasps_coin_1:             COIN | L33 | 10,
    Locations.kreeping_klasps_coin_2:             COIN | L33 | 35,
    Locations.tracker_barrel_trek_coin_1:         COIN | L34 | 4,
    Locations.tracker_barrel_trek_coin_2:         COIN | L34 | 11,
    Locations.tracker_barrel_trek_coin_3:         COIN | L34 | 47,
    Locations.tracker_barrel_trek_coin_4:         COIN | L34 | 66,
    Locations.fish_food_frenzy_coin_1:            COIN | L35 | 8,
    Locations.fish_food_frenzy_coin_2:            COIN | L35 | 54,
    Locations.fireball_frenzy_coin_1:             COIN | L41 | 17,
    Locations.fireball_frenzy_coin_2:             COIN | L41 | 29,
    Locations.fireball_frenzy_coin_3:             COIN | L41 | 54,
    Locations.fireball_frenzy_coin_4:             COIN | L41 | 62,
    Locations.fireball_frenzy_coin_5:             COIN | L41 | 61,
    Locations.demolition_drain_pipe_coin_1:       COIN | L42 | 3,
    Locations.demolition_drain_pipe_coin_2:       COIN | L42 | 12,
    Locations.demolition_drain_pipe_coin_3:       COIN | L42 | 16,
    Locations.demolition_drain_pipe_coin_4:       COIN | L42 | 22,
    Locations.demolition_drain_pipe_coin_5:       COIN | L42 | 69,
    Locations.demolition_drain_pipe_coin_6:       COIN | L42 | 78,
    Locations.demolition_drain_pipe_coin_7:       COIN | L42 | 81,
    Locations.ripsaw_rage_coin_1:                 COIN | L43 | 4,
    Locations.ripsaw_rage_coin_2:                 COIN | L43 | 10,
    Locations.ripsaw_rage_coin_3:                 COIN | L43 | 25,
    Locations.blazing_bazukas_coin_1:             COIN | L44 | 7,
    Locations.blazing_bazukas_coin_2:             COIN | L44 | 26,
    Locations.blazing_bazukas_coin_3:             COIN | L44 | 62,
    Locations.blazing_bazukas_coin_4:             COIN | L44 | 103,
    Locations.low_g_labyrinth_coin_1:             COIN | L45 | 20,
    Locations.low_g_labyrinth_coin_2:             COIN | L45 | 49,
    Locations.low_g_labyrinth_coin_3:             COIN | L45 | 92,
    Locations.low_g_labyrinth_coin_4:             COIN | L45 | 101,
    Locations.low_g_labyrinth_coin_5:             COIN | L45 | 100,
    Locations.low_g_labyrinth_coin_6:             COIN | L45 | 99,
    Locations.low_g_labyrinth_coin_7:             COIN | L45 | 113,
    Locations.krevice_kreepers_coin_1:            COIN | L51 | 11,
    Locations.krevice_kreepers_coin_2:            COIN | L51 | 2,
    Locations.krevice_kreepers_coin_3:            COIN | L51 | 34,
    Locations.krevice_kreepers_coin_4:            COIN | L51 | 65,
    Locations.krevice_kreepers_coin_5:            COIN | L51 | 1,
    Locations.krevice_kreepers_coin_6:            COIN | L51 | 0,
    Locations.tearaway_toboggan_coin_1:           COIN | L52 | 9,
    Locations.tearaway_toboggan_coin_2:           COIN | L52 | 21,
    Locations.tearaway_toboggan_coin_3:           COIN | L52 | 22,
    Locations.tearaway_toboggan_coin_4:           COIN | L52 | 30,
    Locations.tearaway_toboggan_coin_5:           COIN | L52 | 41,
    Locations.tearaway_toboggan_coin_6:           COIN | L52 | 45,
    Locations.barrel_drop_bounce_coin_1:          COIN | L53 | 0,
    Locations.barrel_drop_bounce_coin_2:          COIN | L53 | 24,
    Locations.krackshot_krock_coin_1:             COIN | L54 | 80,
    Locations.krackshot_krock_coin_2:             COIN | L54 | 81,
    Locations.krackshot_krock_coin_3:             COIN | L54 | 59,
    Locations.krackshot_krock_coin_4:             COIN | L54 | 48,
    Locations.krackshot_krock_coin_5:             COIN | L54 | 47,
    Locations.lemguin_lunge_coin_1:               COIN | L55 | 12,
    Locations.lemguin_lunge_coin_2:               COIN | L55 | 36,
    Locations.buzzer_barrage_coin_1:              COIN | L61 | 5,
    Locations.buzzer_barrage_coin_2:              COIN | L61 | 53,
    Locations.buzzer_barrage_coin_3:              COIN | L61 | 91,
    Locations.buzzer_barrage_coin_4:              COIN | L61 | 98,
    Locations.buzzer_barrage_coin_5:              COIN | L61 | 120,
    Locations.buzzer_barrage_coin_6:              COIN | L61 | 125,
    Locations.buzzer_barrage_coin_7:              COIN | L61 | 3,
    Locations.kongfused_cliffs_coin_1:            COIN | L62 | 15,
    Locations.kongfused_cliffs_coin_2:            COIN | L62 | 71,
    Locations.kongfused_cliffs_coin_3:            COIN | L62 | 79,
    Locations.kongfused_cliffs_coin_4:            COIN | L62 | 3,
    Locations.kongfused_cliffs_coin_5:            COIN | L62 | 2,
    Locations.floodlit_fish_coin_1:               COIN | L63 | 48,
    Locations.floodlit_fish_coin_2:               COIN | L63 | 62,
    Locations.floodlit_fish_coin_3:               COIN | L63 | 96,
    Locations.pot_hole_panic_coin_1:              COIN | L64 | 12,
    Locations.pot_hole_panic_coin_2:              COIN | L64 | 52,
    Locations.pot_hole_panic_coin_3:              COIN | L64 | 59,
    Locations.pot_hole_panic_coin_4:              COIN | L64 | 61,
    Locations.ropey_rumpus_coin_1:                COIN | L65 | 0,
    Locations.ropey_rumpus_coin_2:                COIN | L65 | 2,
    Locations.ropey_rumpus_coin_3:                COIN | L65 | 19,
    Locations.ropey_rumpus_coin_4:                COIN | L65 | 38,
    Locations.ropey_rumpus_coin_5:                COIN | L65 | 39,
    Locations.ropey_rumpus_coin_6:                COIN | L65 | 44,
    Locations.ropey_rumpus_coin_7:                COIN | L65 | 48,
    Locations.ropey_rumpus_coin_8:                COIN | L65 | 104,
    Locations.konveyor_rope_klash_coin_1:         COIN | L71 | 3,
    Locations.konveyor_rope_klash_coin_2:         COIN | L71 | 30,
    Locations.konveyor_rope_klash_coin_3:         COIN | L71 | 0,
    Locations.creepy_caverns_coin_1:              COIN | L72 | 1,
    Locations.creepy_caverns_coin_2:              COIN | L72 | 43,
    Locations.creepy_caverns_coin_3:              COIN | L72 | 44,
    Locations.creepy_caverns_coin_4:              COIN | L72 | 84,
    Locations.creepy_caverns_coin_5:              COIN | L72 | 76,
    Locations.creepy_caverns_coin_6:              COIN | L72 | 114,
    Locations.lightning_look_out_coin_1:          COIN | L73 | 0,
    Locations.lightning_look_out_coin_2:          COIN | L73 | 16,
    Locations.lightning_look_out_coin_3:          COIN | L73 | 47,
    Locations.koindozer_klamber_coin_1:           COIN | L74 | 13,
    Locations.koindozer_klamber_coin_2:           COIN | L74 | 0,
    Locations.koindozer_klamber_coin_3:           COIN | L74 | 24,
    Locations.poisonous_pipeline_coin_1:          COIN | L75 | 9,
    Locations.poisonous_pipeline_coin_2:          COIN | L75 | 39,
    Locations.stampede_sprint_coin_1:             COIN | L81 | 40,
    Locations.stampede_sprint_coin_2:             COIN | L81 | 55,
    Locations.criss_kross_cliffs_coin_1:          COIN | L82 | 50,
    Locations.criss_kross_cliffs_coin_2:          COIN | L82 | 36,
    Locations.criss_kross_cliffs_coin_3:          COIN | L82 | 0,
    Locations.criss_kross_cliffs_coin_4:          COIN | L82 | 2,
    Locations.tyrant_twin_tussle_coin_1:          COIN | L83 | 11,
    Locations.tyrant_twin_tussle_coin_2:          COIN | L83 | 23,
    Locations.tyrant_twin_tussle_coin_3:          COIN | L83 | 25,
    Locations.tyrant_twin_tussle_coin_4:          COIN | L83 | 42,
    Locations.tyrant_twin_tussle_coin_5:          COIN | L83 | 79,
    Locations.tyrant_twin_tussle_coin_6:          COIN | L83 | 80,
    Locations.swoopy_salvo_coin_1:                COIN | L84 | 70,
    Locations.rocket_rush_coin_1:                 COIN | L85 | 43,
    Locations.rocket_rush_coin_2:                 COIN | L85 | 47,
    Locations.rocket_rush_coin_3:                 COIN | L85 | 46,
    Locations.rocket_rush_coin_4:                 COIN | L85 | 48,
}

BIRD_NUM = 0x642

banana_birds = {
    Locations.bird_bounty_beach:                  BIRD | 0x646 - BIRD_NUM,
    Locations.bird_kong_cave:                     BIRD | 0x645 - BIRD_NUM,
    Locations.bird_undercover_cove:               BIRD | 0x644 - BIRD_NUM,
    Locations.bird_belchas_burrow:                BIRD | 0x647 - BIRD_NUM,
    Locations.bird_ks_kache:                      BIRD | 0x642 - BIRD_NUM,
    Locations.bird_hill_top_hoard:                BIRD | 0x643 - BIRD_NUM,
    Locations.bird_smugglers_cove:                BIRD | 0x648 - BIRD_NUM,
    Locations.bird_arichs_hoard:                  BIRD | 0x649 - BIRD_NUM,
    Locations.bird_bounty_bay:                    BIRD | 0x64A - BIRD_NUM,
    #Locations.bird_sky_high_secret:               BIRD | 0x64B - BIRD_NUM,
    Locations.bird_glacial_grotto:                BIRD | 0x64C - BIRD_NUM,
    #Locations.bird_clifftop_cache:                BIRD | 0x64D - BIRD_NUM,
    Locations.bird_sewer_stockpile:               BIRD | 0x64E - BIRD_NUM,
}

all_locations = {
    **stage_clears,
    **stage_kong,
    **stage_dk_coins,
    **stage_balloons,
    **stage_bonus,
    **stage_bunches,
    **stage_coins,
}

sorted_locations_table: dict[int, list[int]] = {}
for loc_name, loc_id in all_locations.items():
    level_num = loc_id >> 24
    if level_num not in sorted_locations_table.keys():
        sorted_locations_table[level_num] = []
    sorted_locations_table[level_num].append(loc_id)

all_locations.update(banana_birds)

location_groups = {
    "Lakeside Limbo": {location.value for location in all_locations.keys() if "Lakeside Limbo" in location.value},
    "Doorstop Dash": {location.value for location in all_locations.keys() if "Doorstop Dash" in location.value},
    "Tidal Trouble": {location.value for location in all_locations.keys() if "Tidal Trouble" in location.value},
    "Skidda's Row": {location.value for location in all_locations.keys() if "Skidda's Row" in location.value},
    "Murky Mill": {location.value for location in all_locations.keys() if "Murky Mill" in location.value},
    "Barrel Shield Bust-Up": {location.value for location in all_locations.keys() if "Barrel Shield Bust-Up" in location.value},
    "Riverside Race": {location.value for location in all_locations.keys() if "Riverside Race" in location.value},
    "Squeals on Wheels": {location.value for location in all_locations.keys() if "Squeals on Wheels" in location.value},
    "Springin' Spiders": {location.value for location in all_locations.keys() if "Springin' Spiders" in location.value},
    "Bobbing Barrel Brawl": {location.value for location in all_locations.keys() if "Bobbing Barrel Brawl" in location.value},
    "Bazza's Blockade": {location.value for location in all_locations.keys() if "Bazza's Blockade" in location.value},
    "Rocket Barrel Ride": {location.value for location in all_locations.keys() if "Rocket Barrel Ride" in location.value},
    "Kreeping Klasps": {location.value for location in all_locations.keys() if "Kreeping Klasps" in location.value},
    "Tracker Barrel Trek": {location.value for location in all_locations.keys() if "Tracker Barrel Trek" in location.value},
    "Fish Food Frenzy": {location.value for location in all_locations.keys() if "Fish Food Frenzy" in location.value},
    "Fire-Ball Frenzy": {location.value for location in all_locations.keys() if "Fire-Ball Frenzy" in location.value},
    "Demolition Drain-Pipe": {location.value for location in all_locations.keys() if "Demolition Drain-Pipe" in location.value},
    "Ripsaw Rage": {location.value for location in all_locations.keys() if "Ripsaw Rage" in location.value},
    "Blazing Bazukas": {location.value for location in all_locations.keys() if "Blazing Bazukas" in location.value},
    "Low-G Labyrinth": {location.value for location in all_locations.keys() if "Low-G Labyrinth" in location.value},
    "Krevice Kreepers": {location.value for location in all_locations.keys() if "Krevice Kreepers" in location.value},
    "Tearaway Toboggan": {location.value for location in all_locations.keys() if "Tearaway Toboggan" in location.value},
    "Barrel Drop Bounce": {location.value for location in all_locations.keys() if "Barrel Drop Bounce" in location.value},
    "Krackshot Krock": {location.value for location in all_locations.keys() if "Krackshot Krock" in location.value},
    "Lemguin Lunge": {location.value for location in all_locations.keys() if "Lemguin Lunge" in location.value},
    "Buzzer Barrage": {location.value for location in all_locations.keys() if "Buzzer Barrage" in location.value},
    "Kong-Fused Cliffs": {location.value for location in all_locations.keys() if "Kong-Fused Cliffs" in location.value},
    "Floodlit Fish": {location.value for location in all_locations.keys() if "Floodlit Fish" in location.value},
    "Pot Hole Panic": {location.value for location in all_locations.keys() if "Pot Hole Panic" in location.value},
    "Ropey Rumpus": {location.value for location in all_locations.keys() if "Ropey Rumpus" in location.value},
    "Konveyor Rope Klash": {location.value for location in all_locations.keys() if "Konveyor Rope Klash" in location.value},
    "Creepy Caverns": {location.value for location in all_locations.keys() if "Creepy Caverns" in location.value},
    "Lightning Look-Out": {location.value for location in all_locations.keys() if "Lightning Look-Out" in location.value},
    "Koindozer Klamber": {location.value for location in all_locations.keys() if "Koindozer Klamber" in location.value},
    "Poisonous Pipeline": {location.value for location in all_locations.keys() if "Poisonous Pipeline" in location.value},
    "Stampede Sprint": {location.value for location in all_locations.keys() if "Stampede Sprint" in location.value},
    "Criss Kross Cliffs": {location.value for location in all_locations.keys() if "Criss Kross Cliffs" in location.value},
    "Tyrant Twin Tussle": {location.value for location in all_locations.keys() if "Tyrant Twin Tussle" in location.value},
    "Swoopy Salvo": {location.value for location in all_locations.keys() if "Swoopy Salvo" in location.value},
    "Rocket Rush": {location.value for location in all_locations.keys() if "Rocket Rush" in location.value},
    "Banana Birds": {location.value for location in all_locations.keys() if "Banana Bird" in location.value},
    "Bosses": {
        Locations.belchas_barn_clear.value,
        Locations.arichs_ambush_clear.value,
        Locations.squirt_showdown_clear.value,
        Locations.kaos_karnage_clear.value,
        Locations.bleaks_house_clear.value,
        Locations.barbos_barrier_clear.value,
    },
}


def setup_locations(world: "DKC3World"):
    location_table = {
        **stage_clears,
        **stage_bonus,
    }

    if world.options.kong_checks:
        location_table.update(stage_kong)
    if world.options.dk_coin_checks:
        location_table.update(stage_dk_coins)
    if world.options.balloon_checks:
        location_table.update(stage_balloons)
    if world.options.banana_checks:
        location_table.update(stage_bunches)
    if world.options.coin_checks:
        location_table.update(stage_coins)
    if world.options.bird_checks:
        location_table.update(banana_birds)

    return location_table
