from typing import TYPE_CHECKING

from rule_builder.rules import Has, HasAny, Rule, False_, True_, CanReachLocation
from rule_builder.field_resolvers import FromWorldAttr

if TYPE_CHECKING:
    from . import WarioWareWorld

from .enums import Items, Regions
from .constants import *

class WarioWareRules:
    world: "WarioWareWorld"
    connection_rules: dict[str, Rule]

    def __init__(self, world: "WarioWareWorld") -> None:
        self.player = world.player
        self.world = world

        self.connection_rules = {
            f"Menu -> Credits": Has(Items.flower, count=FromWorldAttr("required_flowers")),

            f"Menu -> {Regions.introduction}": Has(Items.introduction),
            f"Menu -> {Regions.jimmy}": Has(Items.jimmy),
            f"Menu -> {Regions.dribble}": Has(Items.dribble),
            f"Menu -> {Regions.mona}": Has(Items.mona),
            f"Menu -> {Regions.nine_volt}": Has(Items.nine_volt),
            f"Menu -> {Regions.remix_1}": Has(Items.remix_1),
            f"Menu -> {Regions.orbulon}": Has(Items.orbulon),
            f"Menu -> {Regions.crygor}": Has(Items.crygor),
            f"Menu -> {Regions.kat}": Has(Items.kat),
            f"Menu -> {Regions.remix_2}": Has(Items.remix_2),
            f"Menu -> {Regions.wario}": Has(Items.wario),
            f"Menu -> {Regions.easy}": Has(Items.easy),
            f"Menu -> {Regions.thrilling}": Has(Items.thrilling),
            f"Menu -> {Regions.hard}": Has(Items.hard),
            f"Menu -> {Regions.total_boss}": Has(Items.total_boss),
            f"Menu -> {Regions.sheriff_stage}": Has(Items.sheriff_stage),
            f"Menu -> {Regions.dr_wario}": Has(Items.dr_wario),
            f"Menu -> {Regions.fly_swatter}": Has(Items.fly_swatter),
            f"Menu -> {Regions.pyoro}": Has(Items.pyoro),
            f"Menu -> {Regions.pyoro_2}": Has(Items.pyoro_2),
            f"Menu -> {Regions.jump_forever}": Has(Items.jump_forever),
            f"Menu -> {Regions.paper_plane_stage}": Has(Items.paper_plane_stage),
            f"Menu -> {Regions.skating_board}": Has(Items.skating_board),

            f"Menu -> {Regions.crazy_cars}": HasAny(Items.crazy_cars, Items.introduction_bundle),
            f"Menu -> {Regions.repellion}": HasAny(Items.repellion, Items.introduction_bundle),
            f"Menu -> {Regions.wario_whirled}": HasAny(Items.wario_whirled, Items.introduction_bundle),
            f"Menu -> {Regions.dodge_balls}": HasAny(Items.dodge_balls, Items.introduction_bundle),
            f"Menu -> {Regions.saving_face}": HasAny(Items.saving_face, Items.introduction_bundle),
            f"Menu -> {Regions.diamond_dig}": HasAny(Items.diamond_dig, Items.introduction_bundle),
            f"Menu -> {Regions.i_spy}": HasAny(Items.i_spy, Items.introduction_bundle),
            f"Menu -> {Regions.hectic_highway}": HasAny(Items.hectic_highway, Items.introduction_bundle),
            f"Menu -> {Regions.super_wario_bros}": HasAny(Items.super_wario_bros, Items.introduction_bundle),
            f"Menu -> {Regions.the_maze_that_pays}": HasAny(Items.the_maze_that_pays, Items.introduction_bundle),
            f"Menu -> {Regions.mug_shot}": HasAny(Items.mug_shot, Items.introduction_bundle),
            f"Menu -> {Regions.wario_wear}": HasAny(Items.wario_wear, Items.introduction_bundle),
            f"Menu -> {Regions.sparring_wario}": HasAny(Items.sparring_wario, Items.introduction_bundle),

            f"Menu -> {Regions.log_chop}": HasAny(Items.log_chop, Items.jimmy_bundle),
            f"Menu -> {Regions.jumpin_rope}": HasAny(Items.jumpin_rope, Items.jimmy_bundle),
            f"Menu -> {Regions.heads_up}": HasAny(Items.heads_up, Items.jimmy_bundle),
            f"Menu -> {Regions.fruit_shoot}": HasAny(Items.fruit_shoot, Items.jimmy_bundle),
            f"Menu -> {Regions.boing}": HasAny(Items.boing, Items.jimmy_bundle),
            f"Menu -> {Regions.batter_up}": HasAny(Items.batter_up, Items.jimmy_bundle),
            f"Menu -> {Regions.balancing_act}": HasAny(Items.balancing_act, Items.jimmy_bundle),
            f"Menu -> {Regions.spare_me}": HasAny(Items.spare_me, Items.jimmy_bundle),
            f"Menu -> {Regions.mountain_mountin}": HasAny(Items.mountain_mountin, Items.jimmy_bundle),
            f"Menu -> {Regions.pro_curling}": HasAny(Items.pro_curling, Items.jimmy_bundle),
            f"Menu -> {Regions.hammer_toss}": HasAny(Items.hammer_toss, Items.jimmy_bundle),
            f"Menu -> {Regions.ring_my_bell}": HasAny(Items.ring_my_bell, Items.jimmy_bundle),
            f"Menu -> {Regions.hurry_hurdles}": HasAny(Items.hurry_hurdles, Items.jimmy_bundle),
            f"Menu -> {Regions.guy_scraper}": HasAny(Items.guy_scraper, Items.jimmy_bundle),
            f"Menu -> {Regions.baseline_bash}": HasAny(Items.baseline_bash, Items.jimmy_bundle),
            f"Menu -> {Regions.high_hoops}": HasAny(Items.high_hoops, Items.jimmy_bundle),
            f"Menu -> {Regions.gifted_goalie}": HasAny(Items.gifted_goalie, Items.jimmy_bundle),
            f"Menu -> {Regions.lift_n_shout}": HasAny(Items.lift_n_shout, Items.jimmy_bundle),
            f"Menu -> {Regions.ski_jump}": HasAny(Items.ski_jump, Items.jimmy_bundle),
            f"Menu -> {Regions.putt_for_dough}": HasAny(Items.putt_for_dough, Items.jimmy_bundle),
            f"Menu -> {Regions.set_n_spike}": HasAny(Items.set_n_spike, Items.jimmy_bundle),
            f"Menu -> {Regions.city_surfer}": HasAny(Items.city_surfer, Items.jimmy_bundle),
            f"Menu -> {Regions.butterfly_stroke}": HasAny(Items.butterfly_stroke, Items.jimmy_bundle),
            f"Menu -> {Regions.snowboard_slalom}": HasAny(Items.snowboard_slalom, Items.jimmy_bundle),
            f"Menu -> {Regions.punch_out}": HasAny(Items.punch_out, Items.jimmy_bundle),

            f"Menu -> {Regions.space_escape}": HasAny(Items.space_escape, Items.dribble_bundle),
            f"Menu -> {Regions.space_fighter}": HasAny(Items.space_fighter, Items.dribble_bundle),
            f"Menu -> {Regions.arrow_space}": HasAny(Items.arrow_space, Items.dribble_bundle),
            f"Menu -> {Regions.bam_fu}": HasAny(Items.bam_fu, Items.dribble_bundle),
            f"Menu -> {Regions.zero_to_hero}": HasAny(Items.zero_to_hero, Items.dribble_bundle),
            f"Menu -> {Regions.manic_mechanic}": HasAny(Items.manic_mechanic, Items.dribble_bundle),
            f"Menu -> {Regions.hover_for_cover}": HasAny(Items.hover_for_cover, Items.dribble_bundle),
            f"Menu -> {Regions.ufo_assist}": HasAny(Items.ufo_assist, Items.dribble_bundle),
            f"Menu -> {Regions.classic_clash_i}": HasAny(Items.classic_clash_i, Items.dribble_bundle),
            f"Menu -> {Regions.alien_ambush}": HasAny(Items.alien_ambush, Items.dribble_bundle),
            f"Menu -> {Regions.bubble_trouble}": HasAny(Items.bubble_trouble, Items.dribble_bundle),
            f"Menu -> {Regions.mars_ball_destroy}": HasAny(Items.mars_ball_destroy, Items.dribble_bundle),
            f"Menu -> {Regions.classic_clash_ii}": HasAny(Items.classic_clash_ii, Items.dribble_bundle),
            f"Menu -> {Regions.classic_clash_iii}": HasAny(Items.classic_clash_iii, Items.dribble_bundle),
            f"Menu -> {Regions.scooter_commuter}": HasAny(Items.scooter_commuter, Items.dribble_bundle),
            f"Menu -> {Regions.scoot_or_die}": HasAny(Items.scoot_or_die, Items.dribble_bundle),
            f"Menu -> {Regions.tidal_cave}": HasAny(Items.tidal_cave, Items.dribble_bundle),
            f"Menu -> {Regions.slick_wheelie}": HasAny(Items.slick_wheelie, Items.dribble_bundle),
            f"Menu -> {Regions.mars_jars}": HasAny(Items.mars_jars, Items.dribble_bundle),
            f"Menu -> {Regions.super_fly}": HasAny(Items.super_fly, Items.dribble_bundle),
            f"Menu -> {Regions.word_up}": HasAny(Items.word_up, Items.dribble_bundle),
            f"Menu -> {Regions.ninja_pipe_cleaner}": HasAny(Items.ninja_pipe_cleaner, Items.dribble_bundle),
            f"Menu -> {Regions.ninja_vision}": HasAny(Items.ninja_vision, Items.dribble_bundle),
            f"Menu -> {Regions.stick_n_move}": HasAny(Items.stick_n_move, Items.dribble_bundle),
            f"Menu -> {Regions.galaxy_2003}": HasAny(Items.galaxy_2003, Items.dribble_bundle),

            f"Menu -> {Regions.sloppy_salon}": HasAny(Items.sloppy_salon, Items.mona_bundle),
            f"Menu -> {Regions.terminal_velocity}": HasAny(Items.terminal_velocity, Items.mona_bundle),
            f"Menu -> {Regions.dry_eye}": HasAny(Items.dry_eye, Items.mona_bundle),
            f"Menu -> {Regions.right_in_the_eye}": HasAny(Items.right_in_the_eye, Items.mona_bundle),
            f"Menu -> {Regions.paper_plane}": HasAny(Items.paper_plane, Items.mona_bundle),
            f"Menu -> {Regions.crash_test_dummy}": HasAny(Items.crash_test_dummy, Items.mona_bundle),
            f"Menu -> {Regions.page_panic}": HasAny(Items.page_panic, Items.mona_bundle),
            f"Menu -> {Regions.parking_prowess}": HasAny(Items.parking_prowess, Items.mona_bundle),
            f"Menu -> {Regions.butterfingers}": HasAny(Items.butterfingers, Items.mona_bundle),
            f"Menu -> {Regions.pompeii_back}": HasAny(Items.pompeii_back, Items.mona_bundle),
            f"Menu -> {Regions.sunny_side_up}": HasAny(Items.sunny_side_up, Items.mona_bundle),
            f"Menu -> {Regions.gold_digger}": HasAny(Items.gold_digger, Items.mona_bundle),
            f"Menu -> {Regions.air_supplies}": HasAny(Items.air_supplies, Items.mona_bundle),
            f"Menu -> {Regions.tilt_n_tumble}": HasAny(Items.tilt_n_tumble, Items.mona_bundle),
            f"Menu -> {Regions.i_came_i_saw}": HasAny(Items.i_came_i_saw, Items.mona_bundle),
            f"Menu -> {Regions.chicken_pinch}": HasAny(Items.chicken_pinch, Items.mona_bundle),
            f"Menu -> {Regions.noodle_rama}": HasAny(Items.noodle_rama, Items.mona_bundle),
            f"Menu -> {Regions.fries_with_that}": HasAny(Items.fries_with_that, Items.mona_bundle),
            f"Menu -> {Regions.douse_the_house}": HasAny(Items.douse_the_house, Items.mona_bundle),
            f"Menu -> {Regions.sole_man}": HasAny(Items.sole_man, Items.mona_bundle),
            f"Menu -> {Regions.nighttime_allergies}": HasAny(Items.nighttime_allergies, Items.mona_bundle),
            f"Menu -> {Regions.the_brush_off}": HasAny(Items.the_brush_off, Items.mona_bundle),
            f"Menu -> {Regions.boom_box}": HasAny(Items.boom_box, Items.mona_bundle),
            f"Menu -> {Regions.toast_the_ghosts}": HasAny(Items.toast_the_ghosts, Items.mona_bundle),
            f"Menu -> {Regions.nail_call}": HasAny(Items.nail_call, Items.mona_bundle),

            f"Menu -> {Regions.helmet}": HasAny(Items.helmet, Items.nine_volt_bundle),
            f"Menu -> {Regions.chiritorie}": HasAny(Items.chiritorie, Items.nine_volt_bundle),
            f"Menu -> {Regions.lazerblazer}": HasAny(Items.lazerblazer, Items.nine_volt_bundle),
            f"Menu -> {Regions.laser_outlaw}": HasAny(Items.laser_outlaw, Items.nine_volt_bundle),
            f"Menu -> {Regions.hogans_alley}": HasAny(Items.hogans_alley, Items.nine_volt_bundle),
            f"Menu -> {Regions.wild_gunman}": HasAny(Items.wild_gunman, Items.nine_volt_bundle),
            f"Menu -> {Regions.duck_hunt}": HasAny(Items.duck_hunt, Items.nine_volt_bundle),
            f"Menu -> {Regions.balloon_fight}": HasAny(Items.balloon_fight, Items.nine_volt_bundle),
            f"Menu -> {Regions.stack_up}": HasAny(Items.stack_up, Items.nine_volt_bundle),
            f"Menu -> {Regions.donkey_kong}": HasAny(Items.donkey_kong, Items.nine_volt_bundle),
            f"Menu -> {Regions.urban_champion}": HasAny(Items.urban_champion, Items.nine_volt_bundle),
            f"Menu -> {Regions.family_basic}": HasAny(Items.family_basic, Items.nine_volt_bundle),
            f"Menu -> {Regions.mario_clash}": HasAny(Items.mario_clash, Items.nine_volt_bundle),
            f"Menu -> {Regions.mario_paint_fly_swatter}": HasAny(Items.mario_paint_fly_swatter, Items.nine_volt_bundle),
            f"Menu -> {Regions.racing_112}": HasAny(Items.racing_112, Items.nine_volt_bundle),
            f"Menu -> {Regions.metroid}": HasAny(Items.metroid, Items.nine_volt_bundle),
            f"Menu -> {Regions.dr_mario}": HasAny(Items.dr_mario, Items.nine_volt_bundle),
            f"Menu -> {Regions.sheriff}": HasAny(Items.sheriff, Items.nine_volt_bundle),
            f"Menu -> {Regions.the_legend_of_zelda}": HasAny(Items.the_legend_of_zelda, Items.nine_volt_bundle),
            f"Menu -> {Regions.super_mario_bros}": HasAny(Items.super_mario_bros, Items.nine_volt_bundle),
            f"Menu -> {Regions.ultra_hand}": HasAny(Items.ultra_hand, Items.nine_volt_bundle),
            f"Menu -> {Regions.ice_climber}": HasAny(Items.ice_climber, Items.nine_volt_bundle),
            f"Menu -> {Regions.game_boy}": HasAny(Items.game_boy, Items.nine_volt_bundle),
            f"Menu -> {Regions.f_zero}": HasAny(Items.f_zero, Items.nine_volt_bundle),
            f"Menu -> {Regions.ultra_machine}": HasAny(Items.ultra_machine, Items.nine_volt_bundle),

            f"Menu -> {Regions.noodle_cup}": HasAny(Items.noodle_cup, Items.orbulon_bundle),
            f"Menu -> {Regions.odd_man_out}": HasAny(Items.odd_man_out, Items.orbulon_bundle),
            f"Menu -> {Regions.petri_panic}": HasAny(Items.petri_panic, Items.orbulon_bundle),
            f"Menu -> {Regions.electric_groove_fish}": HasAny(Items.electric_groove_fish, Items.orbulon_bundle),
            f"Menu -> {Regions.identity_crisis}": HasAny(Items.identity_crisis, Items.orbulon_bundle),
            f"Menu -> {Regions.sphinx_hijinks}": HasAny(Items.sphinx_hijinks, Items.orbulon_bundle),
            f"Menu -> {Regions.strength_in_numbers}": HasAny(Items.strength_in_numbers, Items.orbulon_bundle),
            f"Menu -> {Regions.maze_daze}": HasAny(Items.maze_daze, Items.orbulon_bundle),
            f"Menu -> {Regions.button_masher}": HasAny(Items.button_masher, Items.orbulon_bundle),
            f"Menu -> {Regions.gear_head_fred}": HasAny(Items.gear_head_fred, Items.orbulon_bundle),
            f"Menu -> {Regions.the_great_cover_cup}": HasAny(Items.the_great_cover_cup, Items.orbulon_bundle),
            f"Menu -> {Regions.getcha_groove_on}": HasAny(Items.getcha_groove_on, Items.orbulon_bundle),
            f"Menu -> {Regions.catterwall}": HasAny(Items.catterwall, Items.orbulon_bundle),
            f"Menu -> {Regions.whats_the_toadal}": HasAny(Items.whats_the_toadal, Items.orbulon_bundle),
            f"Menu -> {Regions.tip_the_scale}": HasAny(Items.tip_the_scale, Items.orbulon_bundle),
            f"Menu -> {Regions.four_leaf_hover}": HasAny(Items.four_leaf_hover, Items.orbulon_bundle),
            f"Menu -> {Regions.find_my_behind}": HasAny(Items.find_my_behind, Items.orbulon_bundle),
            f"Menu -> {Regions.focus_pocus}": HasAny(Items.focus_pocus, Items.orbulon_bundle),
            f"Menu -> {Regions.cavity_calamity}": HasAny(Items.cavity_calamity, Items.orbulon_bundle),
            f"Menu -> {Regions.the_real_mccoy}": HasAny(Items.the_real_mccoy, Items.orbulon_bundle),
            f"Menu -> {Regions.matchboxes}": HasAny(Items.matchboxes, Items.orbulon_bundle),
            f"Menu -> {Regions.praise_or_haze_ii}": HasAny(Items.praise_or_haze_ii, Items.orbulon_bundle),
            f"Menu -> {Regions.code_buster}": HasAny(Items.code_buster, Items.orbulon_bundle),
            f"Menu -> {Regions.garage_rock}": HasAny(Items.garage_rock, Items.orbulon_bundle),
            f"Menu -> {Regions.dungeon_dilemma}": HasAny(Items.dungeon_dilemma, Items.orbulon_bundle),

            f"Menu -> {Regions.bad_man_bash}": HasAny(Items.bad_man_bash, Items.crygor_bundle),
            f"Menu -> {Regions.mirror_mirror}": HasAny(Items.mirror_mirror, Items.crygor_bundle),
            f"Menu -> {Regions.banana_munch}": HasAny(Items.banana_munch, Items.crygor_bundle),
            f"Menu -> {Regions.hard_core}": HasAny(Items.hard_core, Items.crygor_bundle),
            f"Menu -> {Regions.wrong_way_highway}": HasAny(Items.wrong_way_highway, Items.crygor_bundle),
            f"Menu -> {Regions.whoop_de_doodle}": HasAny(Items.whoop_de_doodle, Items.crygor_bundle),
            f"Menu -> {Regions.raging_rhino}": HasAny(Items.raging_rhino, Items.crygor_bundle),
            f"Menu -> {Regions.cymbalism}": HasAny(Items.cymbalism, Items.crygor_bundle),
            f"Menu -> {Regions.mashin_martians}": HasAny(Items.mashin_martians, Items.crygor_bundle),
            f"Menu -> {Regions.quickie_quiz}": HasAny(Items.quickie_quiz, Items.crygor_bundle),
            f"Menu -> {Regions.veg_out}": HasAny(Items.veg_out, Items.crygor_bundle),
            f"Menu -> {Regions.body_block}": HasAny(Items.body_block, Items.crygor_bundle),
            f"Menu -> {Regions.berry_berry_good}": HasAny(Items.berry_berry_good, Items.crygor_bundle),
            f"Menu -> {Regions.funky_fountain}": HasAny(Items.funky_fountain, Items.crygor_bundle),
            f"Menu -> {Regions.cheeky_monkey}": HasAny(Items.cheeky_monkey, Items.crygor_bundle),
            f"Menu -> {Regions.cat_nap}": HasAny(Items.cat_nap, Items.crygor_bundle),
            f"Menu -> {Regions.assembly_line}": HasAny(Items.assembly_line, Items.crygor_bundle),
            f"Menu -> {Regions.whats_your_beef}": HasAny(Items.whats_your_beef, Items.crygor_bundle),
            f"Menu -> {Regions.pod_pinch}": HasAny(Items.pod_pinch, Items.crygor_bundle),
            f"Menu -> {Regions.shake}": HasAny(Items.shake, Items.crygor_bundle),
            f"Menu -> {Regions.spoon_spectacular}": HasAny(Items.spoon_spectacular, Items.crygor_bundle),
            f"Menu -> {Regions.rough_puff}": HasAny(Items.rough_puff, Items.crygor_bundle),
            f"Menu -> {Regions.make_my_clay}": HasAny(Items.make_my_clay, Items.crygor_bundle),
            f"Menu -> {Regions.kettle_mettle}": HasAny(Items.kettle_mettle, Items.crygor_bundle),
            f"Menu -> {Regions.alien_laser_hero}": HasAny(Items.alien_laser_hero, Items.crygor_bundle),

            f"Menu -> {Regions.fruit_fall}": HasAny(Items.fruit_fall, Items.kat_bundle),
            f"Menu -> {Regions.hare_scare}": HasAny(Items.hare_scare, Items.kat_bundle),
            f"Menu -> {Regions.munch_a_bunch}": HasAny(Items.munch_a_bunch, Items.kat_bundle),
            f"Menu -> {Regions.lickety_split}": HasAny(Items.lickety_split, Items.kat_bundle),
            f"Menu -> {Regions.flower_shower}": HasAny(Items.flower_shower, Items.kat_bundle),
            f"Menu -> {Regions.go_fer_the_tater}": HasAny(Items.go_fer_the_tater, Items.kat_bundle),
            f"Menu -> {Regions.picture_perfect}": HasAny(Items.picture_perfect, Items.kat_bundle),
            f"Menu -> {Regions.veggie_might}": HasAny(Items.veggie_might, Items.kat_bundle),
            f"Menu -> {Regions.hoppin_mad}": HasAny(Items.hoppin_mad, Items.kat_bundle),
            f"Menu -> {Regions.bug_bite}": HasAny(Items.bug_bite, Items.kat_bundle),
            f"Menu -> {Regions.mouse_trap}": HasAny(Items.mouse_trap, Items.kat_bundle),
            f"Menu -> {Regions.coconut_catapult}": HasAny(Items.coconut_catapult, Items.kat_bundle),
            f"Menu -> {Regions.disc_o_dog}": HasAny(Items.disc_o_dog, Items.kat_bundle),
            f"Menu -> {Regions.worm_squirm}": HasAny(Items.worm_squirm, Items.kat_bundle),
            f"Menu -> {Regions.kitty_cover}": HasAny(Items.kitty_cover, Items.kat_bundle),
            f"Menu -> {Regions.the_claw}": HasAny(Items.the_claw, Items.kat_bundle),
            f"Menu -> {Regions.penguin_shuffle}": HasAny(Items.penguin_shuffle, Items.kat_bundle),
            f"Menu -> {Regions.spunky_monkey}": HasAny(Items.spunky_monkey, Items.kat_bundle),
            f"Menu -> {Regions.crack_down}": HasAny(Items.crack_down, Items.kat_bundle),
            f"Menu -> {Regions.raaaarrrrggghh}": HasAny(Items.raaaarrrrggghh, Items.kat_bundle),
            f"Menu -> {Regions.crane_game}": HasAny(Items.crane_game, Items.kat_bundle),
            f"Menu -> {Regions.blow_hole_bridge}": HasAny(Items.blow_hole_bridge, Items.kat_bundle),
            f"Menu -> {Regions.two_birds_big_rocks}": HasAny(Items.two_birds_big_rocks, Items.kat_bundle),
            f"Menu -> {Regions.leafy_greens}": HasAny(Items.leafy_greens, Items.kat_bundle),
            f"Menu -> {Regions.the_frog_flap}": HasAny(Items.the_frog_flap, Items.kat_bundle),

            f"Menu -> {Regions.wario_bros}": HasAny(Items.wario_bros, Items.wario_bundle),
            f"Menu -> {Regions.hot_dog_hog}": HasAny(Items.hot_dog_hog, Items.wario_bundle),
            f"Menu -> {Regions.shingle_smasher}": HasAny(Items.shingle_smasher, Items.wario_bundle),
            f"Menu -> {Regions.wario_pinball}": HasAny(Items.wario_pinball, Items.wario_bundle),
            f"Menu -> {Regions.down_n_outie}": HasAny(Items.down_n_outie, Items.wario_bundle),
            f"Menu -> {Regions.laser_vision}": HasAny(Items.laser_vision, Items.wario_bundle),
            f"Menu -> {Regions.thumb_wrestling}": HasAny(Items.thumb_wrestling, Items.wario_bundle),
            f"Menu -> {Regions.hasty_pastry}": HasAny(Items.hasty_pastry, Items.wario_bundle),
            f"Menu -> {Regions.wario_facial}": HasAny(Items.wario_facial, Items.wario_bundle),
            f"Menu -> {Regions.grow_wario_grow}": HasAny(Items.grow_wario_grow, Items.wario_bundle),
            f"Menu -> {Regions.wario_windsock}": HasAny(Items.wario_windsock, Items.wario_bundle),
            f"Menu -> {Regions.loot_scoot}": HasAny(Items.loot_scoot, Items.wario_bundle),
            f"Menu -> {Regions.float_your_boat}": HasAny(Items.float_your_boat, Items.wario_bundle),
            f"Menu -> {Regions.vermin}": HasAny(Items.vermin, Items.wario_bundle),
            f"Menu -> {Regions.mix_n_match}": HasAny(Items.mix_n_match, Items.wario_bundle),
            f"Menu -> {Regions.bug_birdie}": HasAny(Items.bug_birdie, Items.wario_bundle),
            f"Menu -> {Regions.apple_shrapnel}": HasAny(Items.apple_shrapnel, Items.wario_bundle),
            f"Menu -> {Regions.airpain}": HasAny(Items.airpain, Items.wario_bundle),
            f"Menu -> {Regions.unexcite_bike}": HasAny(Items.unexcite_bike, Items.wario_bundle),
            f"Menu -> {Regions.rock_paper_scissors}": HasAny(Items.rock_paper_scissors, Items.wario_bundle),
            f"Menu -> {Regions.high_treeson}": HasAny(Items.high_treeson, Items.wario_bundle),
            f"Menu -> {Regions.wario_kendo}": HasAny(Items.wario_kendo, Items.wario_bundle),
            f"Menu -> {Regions.sinking_feeling}": HasAny(Items.sinking_feeling, Items.wario_bundle),
            f"Menu -> {Regions.produce_pandemonium}": HasAny(Items.produce_pandemonium, Items.wario_bundle),
            f"Menu -> {Regions.warios_adventure}": HasAny(Items.warios_adventure, Items.wario_bundle),
        }

    def set_rules(self) -> None:
        for entrance_name, rule in self.connection_rules.items():
            try:
                entrance = self.world.get_entrance(entrance_name)
                self.world.set_rule(entrance, rule)
            except KeyError:
                continue

        self.world.set_completion_rule(Has(Items.victory))
