from .constants import *
from .enums import Locations, Regions, Items

game_data = {
    Regions.introduction: 0x00,
    Regions.jimmy: 0x08,
    Regions.dribble: 0x18,
    Regions.mona: 0x28,
    Regions.nine_volt: 0x10,
    Regions.remix_1: 0x48,
    Regions.orbulon: 0x38,
    Regions.crygor: 0x30,
    Regions.kat: 0x20,
    Regions.remix_2: 0x50,
    Regions.wario: 0x40,
    Regions.easy: 0x58,
    Regions.thrilling: 0x60,
    Regions.hard: 0x68,
    Regions.total_boss: 0x70,
    Regions.sheriff_stage: 0x78,
    Regions.dr_wario: 0x80,
    Regions.fly_swatter: 0x88,
    Regions.pyoro: 0x90,
    Regions.pyoro_2: 0x98,
    Regions.jump_forever: 0xA0,
    Regions.paper_plane_stage: 0xA8,
    Regions.skating_board: 0xB0,
}

score_only_games = [
    Regions.easy,
    Regions.thrilling,
    Regions.hard,
    Regions.total_boss,
    Regions.sheriff_stage,
    Regions.dr_wario,
    Regions.fly_swatter,
    Regions.pyoro,
    Regions.pyoro_2,
    Regions.jump_forever,
    Regions.paper_plane_stage,
    Regions.skating_board,
]

stages_with_large_scores = [
    game_data[Regions.sheriff_stage],
    game_data[Regions.dr_wario],
    game_data[Regions.pyoro],
    game_data[Regions.pyoro_2],
]

game_scores = {
    Regions.introduction:       [10, 15, 20],
    Regions.jimmy:              [15, 20, 25],
    Regions.dribble:            [25, 30, 35],
    Regions.mona:               [15, 20, 25],
    Regions.nine_volt:          [15, 20, 25],
    Regions.remix_1:            [20, 25, 30],
    Regions.orbulon:            [15, 20, 25],
    Regions.crygor:             [15, 20, 25],
    Regions.kat:                [25, 30, 35],
    Regions.remix_2:            [20, 25, 30],
    Regions.wario:              [25, 30, 35],
    Regions.easy:               [5, 10, 15, 20, 25],
    Regions.thrilling:          [2, 4, 6, 8, 10],
    Regions.hard:               [2, 4, 6, 8, 10],
    Regions.total_boss:         [1, 2, 3, 4, 5],
    Regions.sheriff_stage:      [500, 1000, 1500],
    Regions.dr_wario:           [500, 1000, 1500],
    Regions.fly_swatter:        [20, 35, 50],
    Regions.pyoro:              [1500, 3000, 4500],
    Regions.pyoro_2:            [1500, 3000, 4500],
    Regions.jump_forever:       [10, 30, 50],
    Regions.paper_plane_stage:  [10, 20, 30],
    Regions.skating_board:      [20, 30, 40],
}

microgame_data = {
    Regions.crazy_cars: 0x00,
    Regions.repellion: 0x01,
    Regions.wario_whirled: 0x02,
    Regions.log_chop: 0x03,
    Regions.space_escape: 0x04,
    Regions.jumpin_rope: 0x05,
    Regions.fruit_fall: 0x06,
    Regions.hare_scare: 0x08,
    Regions.munch_a_bunch: 0x09,
    Regions.space_fighter: 0x0A,
    Regions.dodge_balls: 0x0B,
    Regions.saving_face: 0x0C,
    Regions.arrow_space: 0x0D,
    Regions.bam_fu: 0x0E,
    Regions.sloppy_salon: 0x0F,
    Regions.zero_to_hero: 0x10,
    Regions.lickety_split: 0x11,
    Regions.manic_mechanic: 0x12,
    Regions.heads_up: 0x13,
    Regions.diamond_dig: 0x14,
    Regions.terminal_velocity: 0x15,
    Regions.bad_man_bash: 0x16,
    Regions.flower_shower: 0x17,
    Regions.dry_eye: 0x18,
    Regions.go_fer_the_tater: 0x19,
    Regions.picture_perfect: 0x1B,
    Regions.hover_for_cover: 0x1C,
    Regions.right_in_the_eye: 0x1D,
    Regions.paper_plane: 0x1F,
    Regions.fruit_shoot: 0x20,
    Regions.i_spy: 0x21,
    Regions.boing: 0x23,
    Regions.crash_test_dummy: 0x24,
    Regions.helmet: 0x25,
    Regions.page_panic: 0x26,
    Regions.hectic_highway: 0x27,
    Regions.batter_up: 0x28,
    Regions.balancing_act: 0x29,
    Regions.parking_prowess: 0x2A,
    Regions.spare_me: 0x2B,
    Regions.mountain_mountin: 0x2C,
    Regions.pro_curling: 0x2D,
    Regions.hammer_toss: 0x2E,
    Regions.veggie_might: 0x30,
    Regions.ring_my_bell: 0x31,
    Regions.hurry_hurdles: 0x32,
    Regions.hoppin_mad: 0x33,
    Regions.guy_scraper: 0x35,
    Regions.ufo_assist: 0x36,
    Regions.super_wario_bros: 0x37,
    Regions.bug_bite: 0x38,
    Regions.baseline_bash: 0x39,
    Regions.high_hoops: 0x3A,
    Regions.gifted_goalie: 0x3B,
    Regions.chiritorie: 0x3C,
    Regions.lift_n_shout: 0x3E,
    Regions.ski_jump: 0x3F,
    Regions.the_maze_that_pays: 0x40,
    Regions.butterfingers: 0x42,
    Regions.classic_clash_i: 0x43,
    Regions.mouse_trap: 0x44,
    Regions.alien_ambush: 0x45,
    Regions.lazerblazer: 0x46,
    Regions.putt_for_dough: 0x47,
    Regions.bubble_trouble: 0x48,
    Regions.laser_outlaw: 0x49,
    Regions.hogans_alley: 0x4A,
    Regions.mug_shot: 0x4B,
    Regions.mars_ball_destroy: 0x4C,
    Regions.wild_gunman: 0x4D,
    Regions.duck_hunt: 0x4E,
    Regions.classic_clash_ii: 0x4F,
    Regions.pompeii_back: 0x50,
    Regions.balloon_fight: 0x51,
    Regions.coconut_catapult: 0x52,
    Regions.sunny_side_up: 0x54,
    Regions.classic_clash_iii: 0x55,
    Regions.gold_digger: 0x56,
    Regions.stack_up: 0x57,
    Regions.scooter_commuter: 0x58,
    Regions.air_supplies: 0x59,
    Regions.donkey_kong: 0x5A,
    Regions.scoot_or_die: 0x5B,
    Regions.tilt_n_tumble: 0x5C,
    Regions.urban_champion: 0x5D,
    Regions.family_basic: 0x5F,
    Regions.tidal_cave: 0x60,
    Regions.i_came_i_saw: 0x61,
    Regions.slick_wheelie: 0x62,
    Regions.mario_clash: 0x63,
    Regions.chicken_pinch: 0x64,
    Regions.mario_paint_fly_swatter: 0x65,
    Regions.mars_jars: 0x67,
    Regions.super_fly: 0x68,
    Regions.noodle_rama: 0x69,
    Regions.racing_112: 0x6A,
    Regions.word_up: 0x6B,
    Regions.metroid: 0x6C,
    Regions.fries_with_that: 0x6D,
    Regions.dr_mario: 0x6E,
    Regions.disc_o_dog: 0x6F,
    Regions.wario_wear: 0x70,
    Regions.ninja_pipe_cleaner: 0x71,
    Regions.sheriff: 0x72,
    Regions.the_legend_of_zelda: 0x73,
    Regions.douse_the_house: 0x74,
    Regions.sole_man: 0x75,
    Regions.mirror_mirror: 0x76,
    Regions.banana_munch: 0x77,
    Regions.worm_squirm: 0x78,
    Regions.super_mario_bros: 0x79,
    Regions.kitty_cover: 0x7A,
    Regions.the_claw: 0x7B,
    Regions.nighttime_allergies: 0x7C,
    Regions.hard_core: 0x7D,
    Regions.the_brush_off: 0x7E,
    Regions.penguin_shuffle: 0x7F,
    Regions.wrong_way_highway: 0x80,
    Regions.boom_box: 0x81,
    Regions.ninja_vision: 0x82,
    Regions.spunky_monkey: 0x83,
    Regions.toast_the_ghosts: 0x84,
    Regions.ultra_hand: 0x85,
    Regions.set_n_spike: 0x86,
    Regions.city_surfer: 0x87,
    Regions.crack_down: 0x88,
    Regions.butterfly_stroke: 0x89,
    Regions.snowboard_slalom: 0x8A,
    Regions.whoop_de_doodle: 0x8B,
    Regions.raging_rhino: 0x8C,
    Regions.cymbalism: 0x8D,
    Regions.mashin_martians: 0x8E,
    Regions.raaaarrrrggghh: 0x8F,
    Regions.quickie_quiz: 0x90,
    Regions.veg_out: 0x91,
    Regions.body_block: 0x92,
    Regions.berry_berry_good: 0x93,
    Regions.funky_fountain: 0x94,
    Regions.stick_n_move: 0x95,
    Regions.cheeky_monkey: 0x96,
    Regions.cat_nap: 0x97,
    Regions.assembly_line: 0x98,
    Regions.crane_game: 0x99,
    Regions.whats_your_beef: 0x9A,
    Regions.wario_bros: 0x9B,
    Regions.pod_pinch: 0x9C,
    Regions.blow_hole_bridge: 0x9D,
    Regions.hot_dog_hog: 0x9E,
    Regions.two_birds_big_rocks: 0x9F,
    Regions.shingle_smasher: 0xA0,
    Regions.wario_pinball: 0xA1,
    Regions.down_n_outie: 0xA2,
    Regions.laser_vision: 0xA3,
    Regions.thumb_wrestling: 0xA4,
    Regions.hasty_pastry: 0xA5,
    Regions.wario_facial: 0xA6,
    Regions.grow_wario_grow: 0xA7,
    Regions.shake: 0xA8,
    Regions.wario_windsock: 0xA9,
    Regions.loot_scoot: 0xAA,
    Regions.float_your_boat: 0xAB,
    Regions.vermin: 0xAC,
    Regions.mix_n_match: 0xAD,
    Regions.bug_birdie: 0xAE,
    Regions.apple_shrapnel: 0xAF,
    Regions.airpain: 0xB0,
    Regions.unexcite_bike: 0xB1,
    Regions.rock_paper_scissors: 0xB2,
    Regions.spoon_spectacular: 0xB3,
    Regions.high_treeson: 0xB4,
    Regions.leafy_greens: 0xB5,
    Regions.rough_puff: 0xB6,
    Regions.make_my_clay: 0xB7,
    Regions.wario_kendo: 0xB8,
    Regions.sinking_feeling: 0xB9,
    Regions.kettle_mettle: 0xBA,
    Regions.ice_climber: 0xBB,
    Regions.game_boy: 0xBC,
    Regions.produce_pandemonium: 0xBD,
    Regions.f_zero: 0xBE,
    Regions.noodle_cup: 0xBF,
    Regions.odd_man_out: 0xC0,
    Regions.petri_panic: 0xC1,
    Regions.electric_groove_fish: 0xC2,
    Regions.identity_crisis: 0xC3,
    Regions.sphinx_hijinks: 0xC4,
    Regions.strength_in_numbers: 0xC5,
    Regions.maze_daze: 0xC6,
    Regions.button_masher: 0xC7,
    Regions.gear_head_fred: 0xC8,
    Regions.the_great_cover_cup: 0xC9,
    Regions.getcha_groove_on: 0xCA,
    Regions.catterwall: 0xCB,
    Regions.whats_the_toadal: 0xCC,
    Regions.tip_the_scale: 0xCD,
    Regions.four_leaf_hover: 0xCE,
    Regions.find_my_behind: 0xCF,
    Regions.focus_pocus: 0xD0,
    Regions.cavity_calamity: 0xD1,
    Regions.the_real_mccoy: 0xD2,
    Regions.matchboxes: 0xD3,
    Regions.praise_or_haze_ii: 0xD4,
    Regions.code_buster: 0xD5,
    Regions.garage_rock: 0xD6,
    Regions.ultra_machine: 0xD7,
    Regions.punch_out: 0xD9,
    Regions.nail_call: 0xDA,
    Regions.galaxy_2003: 0xDB,
    Regions.sparring_wario: 0xDC,
    Regions.dungeon_dilemma: 0xDD,
    Regions.the_frog_flap: 0xDF,
    Regions.alien_laser_hero: 0xE0,
    Regions.warios_adventure: 0xE1,
}

reversed_microgame_data = {v: k for k, v in microgame_data.items()}

game_groups = {
    Items.introduction_bundle: [
        Regions.crazy_cars.value,
        Regions.repellion.value,
        Regions.wario_whirled.value,
        Regions.dodge_balls.value,
        Regions.saving_face.value,
        Regions.diamond_dig.value,
        Regions.i_spy.value,
        Regions.hectic_highway.value,
        Regions.super_wario_bros.value,
        Regions.the_maze_that_pays.value,
        Regions.mug_shot.value,
        Regions.wario_wear.value,
        Regions.sparring_wario.value,
    ],
    Items.jimmy_bundle: [
        Regions.log_chop.value,
        Regions.jumpin_rope.value,
        Regions.heads_up.value,
        Regions.fruit_shoot.value,
        Regions.boing.value,
        Regions.batter_up.value,
        Regions.balancing_act.value,
        Regions.spare_me.value,
        Regions.mountain_mountin.value,
        Regions.pro_curling.value,
        Regions.hammer_toss.value,
        Regions.ring_my_bell.value,
        Regions.hurry_hurdles.value,
        Regions.guy_scraper.value,
        Regions.baseline_bash.value,
        Regions.high_hoops.value,
        Regions.gifted_goalie.value,
        Regions.lift_n_shout.value,
        Regions.ski_jump.value,
        Regions.putt_for_dough.value,
        Regions.set_n_spike.value,
        Regions.city_surfer.value,
        Regions.butterfly_stroke.value,
        Regions.snowboard_slalom.value,
        Regions.punch_out.value,
    ],
    Items.dribble_bundle: [
        Regions.space_escape.value,
        Regions.space_fighter.value,
        Regions.arrow_space.value,
        Regions.bam_fu.value,
        Regions.zero_to_hero.value,
        Regions.manic_mechanic.value,
        Regions.hover_for_cover.value,
        Regions.ufo_assist.value,
        Regions.classic_clash_i.value,
        Regions.alien_ambush.value,
        Regions.bubble_trouble.value,
        Regions.mars_ball_destroy.value,
        Regions.classic_clash_ii.value,
        Regions.classic_clash_iii.value,
        Regions.scooter_commuter.value,
        Regions.scoot_or_die.value,
        Regions.tidal_cave.value,
        Regions.slick_wheelie.value,
        Regions.mars_jars.value,
        Regions.super_fly.value,
        Regions.word_up.value,
        Regions.ninja_pipe_cleaner.value,
        Regions.ninja_vision.value,
        Regions.stick_n_move.value,
        Regions.galaxy_2003.value,
    ],
    Items.mona_bundle: [
        Regions.sloppy_salon.value,
        Regions.terminal_velocity.value,
        Regions.dry_eye.value,
        Regions.right_in_the_eye.value,
        Regions.paper_plane.value,
        Regions.crash_test_dummy.value,
        Regions.page_panic.value,
        Regions.parking_prowess.value,
        Regions.butterfingers.value,
        Regions.pompeii_back.value,
        Regions.sunny_side_up.value,
        Regions.gold_digger.value,
        Regions.air_supplies.value,
        Regions.tilt_n_tumble.value,
        Regions.i_came_i_saw.value,
        Regions.chicken_pinch.value,
        Regions.noodle_rama.value,
        Regions.fries_with_that.value,
        Regions.douse_the_house.value,
        Regions.sole_man.value,
        Regions.nighttime_allergies.value,
        Regions.the_brush_off.value,
        Regions.boom_box.value,
        Regions.toast_the_ghosts.value,
        Regions.nail_call.value,
    ],
    Items.nine_volt_bundle: [
        Regions.helmet.value,
        Regions.chiritorie.value,
        Regions.lazerblazer.value,
        Regions.laser_outlaw.value,
        Regions.hogans_alley.value,
        Regions.wild_gunman.value,
        Regions.duck_hunt.value,
        Regions.balloon_fight.value,
        Regions.stack_up.value,
        Regions.donkey_kong.value,
        Regions.urban_champion.value,
        Regions.family_basic.value,
        Regions.mario_clash.value,
        Regions.mario_paint_fly_swatter.value,
        Regions.racing_112.value,
        Regions.metroid.value,
        Regions.dr_mario.value,
        Regions.sheriff.value,
        Regions.the_legend_of_zelda.value,
        Regions.super_mario_bros.value,
        Regions.ultra_hand.value,
        Regions.ice_climber.value,
        Regions.game_boy.value,
        Regions.f_zero.value,
        Regions.ultra_machine.value,
    ],
    Items.orbulon_bundle: [
        Regions.noodle_cup.value,
        Regions.odd_man_out.value,
        Regions.petri_panic.value,
        Regions.electric_groove_fish.value,
        Regions.identity_crisis.value,
        Regions.sphinx_hijinks.value,
        Regions.strength_in_numbers.value,
        Regions.maze_daze.value,
        Regions.button_masher.value,
        Regions.gear_head_fred.value,
        Regions.the_great_cover_cup.value,
        Regions.getcha_groove_on.value,
        Regions.catterwall.value,
        Regions.whats_the_toadal.value,
        Regions.tip_the_scale.value,
        Regions.four_leaf_hover.value,
        Regions.find_my_behind.value,
        Regions.focus_pocus.value,
        Regions.cavity_calamity.value,
        Regions.the_real_mccoy.value,
        Regions.matchboxes.value,
        Regions.praise_or_haze_ii.value,
        Regions.code_buster.value,
        Regions.garage_rock.value,
        Regions.dungeon_dilemma.value,
    ],
    Items.crygor_bundle: [
        Regions.bad_man_bash.value,
        Regions.mirror_mirror.value,
        Regions.banana_munch.value,
        Regions.hard_core.value,
        Regions.wrong_way_highway.value,
        Regions.whoop_de_doodle.value,
        Regions.raging_rhino.value,
        Regions.cymbalism.value,
        Regions.mashin_martians.value,
        Regions.quickie_quiz.value,
        Regions.veg_out.value,
        Regions.body_block.value,
        Regions.berry_berry_good.value,
        Regions.funky_fountain.value,
        Regions.cheeky_monkey.value,
        Regions.cat_nap.value,
        Regions.assembly_line.value,
        Regions.whats_your_beef.value,
        Regions.pod_pinch.value,
        Regions.shake.value,
        Regions.spoon_spectacular.value,
        Regions.rough_puff.value,
        Regions.make_my_clay.value,
        Regions.kettle_mettle.value,
        Regions.alien_laser_hero.value,
    ],
    Items.kat_bundle: [
        Regions.fruit_fall.value,
        Regions.hare_scare.value,
        Regions.munch_a_bunch.value,
        Regions.lickety_split.value,
        Regions.flower_shower.value,
        Regions.go_fer_the_tater.value,
        Regions.picture_perfect.value,
        Regions.veggie_might.value,
        Regions.hoppin_mad.value,
        Regions.bug_bite.value,
        Regions.mouse_trap.value,
        Regions.coconut_catapult.value,
        Regions.disc_o_dog.value,
        Regions.worm_squirm.value,
        Regions.kitty_cover.value,
        Regions.the_claw.value,
        Regions.penguin_shuffle.value,
        Regions.spunky_monkey.value,
        Regions.crack_down.value,
        Regions.raaaarrrrggghh.value,
        Regions.crane_game.value,
        Regions.blow_hole_bridge.value,
        Regions.two_birds_big_rocks.value,
        Regions.leafy_greens.value,
        Regions.the_frog_flap.value,
    ],
    Items.wario_bundle: [
        Regions.wario_bros.value,
        Regions.hot_dog_hog.value,
        Regions.shingle_smasher.value,
        Regions.wario_pinball.value,
        Regions.down_n_outie.value,
        Regions.laser_vision.value,
        Regions.thumb_wrestling.value,
        Regions.hasty_pastry.value,
        Regions.wario_facial.value,
        Regions.grow_wario_grow.value,
        Regions.wario_windsock.value,
        Regions.loot_scoot.value,
        Regions.float_your_boat.value,
        Regions.vermin.value,
        Regions.mix_n_match.value,
        Regions.bug_birdie.value,
        Regions.apple_shrapnel.value,
        Regions.airpain.value,
        Regions.unexcite_bike.value,
        Regions.rock_paper_scissors.value,
        Regions.high_treeson.value,
        Regions.wario_kendo.value,
        Regions.sinking_feeling.value,
        Regions.produce_pandemonium.value,
        Regions.warios_adventure.value,
    ],
}