logic_tricks = [
    "Yoshi's Island 4 - Dragon Coin Sacrifice",
    "Donut Plains 1 - Yoshi Jump to Key",
    "Donut Ghost House - Spin Jump off Boo",
    "Vanilla Dome 1 - Itemless Sinking Platform",
    "Vanilla Dome 2 - Climbless Secret via Yoshi and Midway",
    "Vanilla Dome 3 - Bonus Room Wall Running",
    "Vanilla Dome 4 - Sacrifice for Coin Block #8",
    "Vanilla Secret 1 - Wall Running",
    "Vanilla Secret 3 - Swimless",
    "Lemmy's Castle - Itemless 1-Up blocks",
    "Cheese Bridge Area - Secret Exit with Yoshi",
    "Ludwig's Castle - Runless",
    "Ludwig's Castle - Climbless",
    "Forest of Illusion 1 - Secret Exit with Yoshi",
    "Forest of Illusion 1 - Secret Exit with Cape",
    "Forest of Illusion 3 - Can pass big pipe itemless",
    "Forest of Illusion 3 - Secret Exit with Yoshi",
    "Forest Ghost House - Skip second room",
    "Forest Secret Area - Itemless 1-Up block",
    "Chocolate Island 1 - Damage Boost Past Munchers",
    "Chocolate Island 4 - Perfect Dragon Coin Timing",
    "Sunken Ghost Ship - Free Falling Dragon Coins",
    "Valley of Bowser 1 - Bonus Room Yoshi Jump",
    "Valley of Bowser 3 - Itemless Powerup block",
    "Valley of Bowser 4 - Yoshi Climb",
    "Valley of Bowser 4 - Climbless Secret via Yoshi and Midway",
    "Valley Ghost House - True Carryless Secret Exit",
    "Star World 3 - Top area with a Star",
    "Star World 4 - Carryless exit with wingless Yoshi",
    "Gnarly - Climbless with Flight",
    "Awesome - Itemless",
    "Mondo - Swimless",
    "Outrageous - Wall Run pipe",
]
