logic_tricks = [
    "Vanilla Dome 1 - Itemless Sinking Platform",
    "Vanilla Dome 4 - Sacrifice for Coin Block #8",
    "Vanilla Secret 1 - Wall Running",
    "Vanilla Secret 3 - Swimless",
    "Lemmy's Castle - Itemless 1-Up blocks",
    "Butter Bridge 1 - No Red Switch Palace",
    "Cheese Bridge Area - Secret Exit with Yoshi",
    "Ludwig's Castle - Runless",
    "Ludwig's Castle - Climbless",
    "Forest of Illusion 1 - Secret Exit with Yoshi",
    "Forest of Illusion 3 - Can pass big pipe itemless",
    "Forest of Illusion 3 - Secret Exit with Yoshi",
    "Forest Ghost House - Skip second room",
    "Forest Secret Area - Itemless 1-Up block",
    "Valley of Bowser 3 - Itemless Powerup block",
    "Valley of Bowser 4 - Yoshi Climb",
    "Valley Ghost House - True Carryless Secret Exit",
    "Star World 3 - Top area with a Star",
    "Star World 4 - Carryless Secret Exit with Yoshi sacrifice",
    "Awesome - Itemless",
    "Mondo - Swimless",
    "Outrageous - Wall Run pipe",
]
