from typing import TYPE_CHECKING

from rule_builder.rules import Has, HasAny, Rule
from rule_builder.field_resolvers import FromWorldAttr

if TYPE_CHECKING:
    from . import WarioTwistedWorld

from .enums import Items, Regions
from .constants import *

class WarioTwistedRules:
    world: "WarioTwistedWorld"
    connection_rules: dict[str, Rule]

    def __init__(self, world: "WarioTwistedWorld") -> None:
        self.player = world.player
        self.world = world

        self.connection_rules = {
            f"Menu -> Credits": Has(Items.crown, count=FromWorldAttr("required_crowns")),

            f"Menu -> {Regions.wario}": Has(Items.wario),
            f"Menu -> {Regions.mona}": Has(Items.mona),
            f"Menu -> {Regions.jimmy}": Has(Items.jimmy),
            f"Menu -> {Regions.kat_ana}": Has(Items.kat_ana),
            f"Menu -> {Regions.dribble}": Has(Items.dribble),
            f"Menu -> {Regions.crygor}": Has(Items.crygor),
            f"Menu -> {Regions.orbulon}": Has(Items.orbulon),
            f"Menu -> {Regions.nine_volt}": Has(Items.nine_volt),
            f"Menu -> {Regions.wario_man}": Has(Items.wario_man),
            f"Menu -> {Regions.jimmy_folks}": Has(Items.jimmy_folks),
            f"Menu -> {Regions.wariowatch}": Has(Items.wariowatch),
            f"Menu -> {Regions.wariowatch_2}": Has(Items.wariowatch_2),
            f"Menu -> {Regions.skyscraper}": Has(Items.skyscraper),
            f"Menu -> {Regions.tower}": Has(Items.tower),
            f"Menu -> {Regions.mansion}": Has(Items.mansion),

            f"Menu -> {Regions.tiptoe_titan}": HasAny(Items.tiptoe_titan, Items.wario_man_bundle),
            f"Menu -> {Regions.rain_of_riches}": HasAny(Items.rain_of_riches, Items.wario_man_bundle),
            f"Menu -> {Regions.power_line_pigeons}": HasAny(Items.power_line_pigeons, Items.wario_man_bundle),
            f"Menu -> {Regions.burying_the_hatchet}": HasAny(Items.burying_the_hatchet, Items.wario_man_bundle),
            f"Menu -> {Regions.crash_prize}": HasAny(Items.crash_prize, Items.wario_man_bundle),
            f"Menu -> {Regions.hot_rod}": HasAny(Items.hot_rod, Items.wario_man_bundle),
            f"Menu -> {Regions.rock_it}": HasAny(Items.rock_it, Items.wario_man_bundle),
            f"Menu -> {Regions.ping_pong_panic}": HasAny(Items.ping_pong_panic, Items.wario_man_bundle),
            f"Menu -> {Regions.catch_of_the_day}": HasAny(Items.catch_of_the_day, Items.wario_man_bundle),
            f"Menu -> {Regions.no_zone}": HasAny(Items.no_zone, Items.wario_man_bundle),
            f"Menu -> {Regions.alignment}": HasAny(Items.alignment, Items.wario_man_bundle),
            f"Menu -> {Regions.swamp_swing}": HasAny(Items.swamp_swing, Items.wario_man_bundle),
            f"Menu -> {Regions.drywall_dodge}": HasAny(Items.drywall_dodge, Items.wario_man_bundle),
            f"Menu -> {Regions.super_wario}": HasAny(Items.super_wario, Items.wario_man_bundle),
            f"Menu -> {Regions.cyclone_kick}": HasAny(Items.cyclone_kick, Items.wario_man_bundle),
            f"Menu -> {Regions.wario_weigh_in}": HasAny(Items.wario_weigh_in, Items.wario_man_bundle),
            f"Menu -> {Regions.going_steady}": HasAny(Items.going_steady, Items.wario_man_bundle),
            f"Menu -> {Regions.inch_worm}": HasAny(Items.inch_worm, Items.wario_man_bundle),
            f"Menu -> {Regions.soda_jerk}": HasAny(Items.soda_jerk, Items.wario_man_bundle),
            f"Menu -> {Regions.robotomy}": HasAny(Items.robotomy, Items.wario_man_bundle),
            f"Menu -> {Regions.wee_wario_blast}": HasAny(Items.wee_wario_blast, Items.wario_man_bundle),
            f"Menu -> {Regions.fragile}": HasAny(Items.fragile, Items.wario_man_bundle),
            f"Menu -> {Regions.strange_ritual}": HasAny(Items.strange_ritual, Items.wario_man_bundle),
            f"Menu -> {Regions.wario_hockey}": HasAny(Items.wario_hockey, Items.wario_man_bundle),
            f"Menu -> {Regions.wario_and_the_beanstalk}": HasAny(Items.wario_and_the_beanstalk, Items.wario_man_bundle),
            f"Menu -> {Regions.stay_in_school}": HasAny(Items.stay_in_school, Items.wario_man_bundle),
            f"Menu -> {Regions.high_speed_chase}": HasAny(Items.high_speed_chase, Items.wario_man_bundle),
            f"Menu -> {Regions.volt_bolt}": HasAny(Items.volt_bolt, Items.wario_man_bundle),
            f"Menu -> {Regions.wario_mambo}": HasAny(Items.wario_mambo, Items.wario_man_bundle),

            f"Menu -> {Regions.pipe_puzzle}": HasAny(Items.pipe_puzzle, Items.orbulon_bundle),
            f"Menu -> {Regions.air_passage}": HasAny(Items.air_passage, Items.orbulon_bundle),
            f"Menu -> {Regions.tapped_out}": HasAny(Items.tapped_out, Items.orbulon_bundle),
            f"Menu -> {Regions.dire_plates}": HasAny(Items.dire_plates, Items.orbulon_bundle),
            f"Menu -> {Regions.deadly_ditty}": HasAny(Items.deadly_ditty, Items.orbulon_bundle),
            f"Menu -> {Regions.alphabet_soup}": HasAny(Items.alphabet_soup, Items.orbulon_bundle),
            f"Menu -> {Regions.manual_labor}": HasAny(Items.manual_labor, Items.orbulon_bundle),
            f"Menu -> {Regions.fine_tune}": HasAny(Items.fine_tune, Items.orbulon_bundle),
            f"Menu -> {Regions.green_thumb}": HasAny(Items.green_thumb, Items.orbulon_bundle),
            f"Menu -> {Regions.wedgies}": HasAny(Items.wedgies, Items.orbulon_bundle),
            f"Menu -> {Regions.boomerang}": HasAny(Items.boomerang, Items.orbulon_bundle),
            f"Menu -> {Regions.fill_in_the_blanks}": HasAny(Items.fill_in_the_blanks, Items.orbulon_bundle),
            f"Menu -> {Regions.peak_peek}": HasAny(Items.peak_peek, Items.orbulon_bundle),
            f"Menu -> {Regions.connect_the_dots}": HasAny(Items.connect_the_dots, Items.orbulon_bundle),
            f"Menu -> {Regions.rocket_rotary}": HasAny(Items.rocket_rotary, Items.orbulon_bundle),
            f"Menu -> {Regions.sleight_of_hand}": HasAny(Items.sleight_of_hand, Items.orbulon_bundle),
            f"Menu -> {Regions.guitar_solo}": HasAny(Items.guitar_solo, Items.orbulon_bundle),
            f"Menu -> {Regions.produce_pick}": HasAny(Items.produce_pick, Items.orbulon_bundle),
            f"Menu -> {Regions.about_face}": HasAny(Items.about_face, Items.orbulon_bundle),
            f"Menu -> {Regions.safecracker}": HasAny(Items.safecracker, Items.orbulon_bundle),
            f"Menu -> {Regions.high_card_draw}": HasAny(Items.high_card_draw, Items.orbulon_bundle),
            f"Menu -> {Regions.toaster_jam}": HasAny(Items.toaster_jam, Items.orbulon_bundle),
            f"Menu -> {Regions.crossing_guard}": HasAny(Items.crossing_guard, Items.orbulon_bundle),

            f"Menu -> {Regions.hats_off}": HasAny(Items.hats_off, Items.crygor_bundle),
            f"Menu -> {Regions.tiltillation}": HasAny(Items.tiltillation, Items.crygor_bundle),
            f"Menu -> {Regions.crescent_roll}": HasAny(Items.crescent_roll, Items.crygor_bundle),
            f"Menu -> {Regions.power_outage}": HasAny(Items.power_outage, Items.crygor_bundle),
            f"Menu -> {Regions.mooo_ve_it}": HasAny(Items.mooo_ve_it, Items.crygor_bundle),
            f"Menu -> {Regions.gravi_key}": HasAny(Items.gravi_key, Items.crygor_bundle),
            f"Menu -> {Regions.half_full}": HasAny(Items.half_full, Items.crygor_bundle),
            f"Menu -> {Regions.cliff_hanger}": HasAny(Items.cliff_hanger, Items.crygor_bundle),
            f"Menu -> {Regions.shake_down}": HasAny(Items.shake_down, Items.crygor_bundle),
            f"Menu -> {Regions.heartwrench}": HasAny(Items.heartwrench, Items.crygor_bundle),
            f"Menu -> {Regions.trash_day}": HasAny(Items.trash_day, Items.crygor_bundle),
            f"Menu -> {Regions.half_empty}": HasAny(Items.half_empty, Items.crygor_bundle),
            f"Menu -> {Regions.spout_off}": HasAny(Items.spout_off, Items.crygor_bundle),
            f"Menu -> {Regions.aromatherapy}": HasAny(Items.aromatherapy, Items.crygor_bundle),
            f"Menu -> {Regions.skid_road}": HasAny(Items.skid_road, Items.crygor_bundle),
            f"Menu -> {Regions.balloonatic}": HasAny(Items.balloonatic, Items.crygor_bundle),
            f"Menu -> {Regions.spitfall}": HasAny(Items.spitfall, Items.crygor_bundle),
            f"Menu -> {Regions.what_goes_in}": HasAny(Items.what_goes_in, Items.crygor_bundle),
            f"Menu -> {Regions.open_and_shut_case}": HasAny(Items.open_and_shut_case, Items.crygor_bundle),
            f"Menu -> {Regions.shower_power}": HasAny(Items.shower_power, Items.crygor_bundle),
            f"Menu -> {Regions.stumblebot}": HasAny(Items.stumblebot, Items.crygor_bundle),

            f"Menu -> {Regions.down_in_the_dumps}": HasAny(Items.down_in_the_dumps, Items.jimmy_bundle),
            f"Menu -> {Regions.feel_the_burn}": HasAny(Items.feel_the_burn, Items.jimmy_bundle),
            f"Menu -> {Regions.night_and_day}": HasAny(Items.night_and_day, Items.jimmy_bundle),
            f"Menu -> {Regions.slam_dunk}": HasAny(Items.slam_dunk, Items.jimmy_bundle),
            f"Menu -> {Regions.dishpan_hands}": HasAny(Items.dishpan_hands, Items.jimmy_bundle),
            f"Menu -> {Regions.net_profits}": HasAny(Items.net_profits, Items.jimmy_bundle),
            f"Menu -> {Regions.focus_pocus}": HasAny(Items.focus_pocus, Items.jimmy_bundle),
            f"Menu -> {Regions.beware_of_dog}": HasAny(Items.beware_of_dog, Items.jimmy_bundle),
            f"Menu -> {Regions.circular_logic}": HasAny(Items.circular_logic, Items.jimmy_bundle),
            f"Menu -> {Regions.h2_whoa}": HasAny(Items.h2_whoa, Items.jimmy_bundle),
            f"Menu -> {Regions.twist_and_sprout}": HasAny(Items.twist_and_sprout, Items.jimmy_bundle),
            f"Menu -> {Regions.bacon_patron}": HasAny(Items.bacon_patron, Items.jimmy_bundle),
            f"Menu -> {Regions.make_way_for_martian}": HasAny(Items.make_way_for_martian, Items.jimmy_bundle),
            f"Menu -> {Regions.stab_in_the_dark}": HasAny(Items.stab_in_the_dark, Items.jimmy_bundle),
            f"Menu -> {Regions.self_defense}": HasAny(Items.self_defense, Items.jimmy_bundle),
            f"Menu -> {Regions.bright_idea}": HasAny(Items.bright_idea, Items.jimmy_bundle),
            f"Menu -> {Regions.dig_this}": HasAny(Items.dig_this, Items.jimmy_bundle),
            f"Menu -> {Regions.daily_grind}": HasAny(Items.daily_grind, Items.jimmy_bundle),
            f"Menu -> {Regions.ice_queen}": HasAny(Items.ice_queen, Items.jimmy_bundle),
            f"Menu -> {Regions.save_our_raft}": HasAny(Items.save_our_raft, Items.jimmy_bundle),
            f"Menu -> {Regions.fashion_plate}": HasAny(Items.fashion_plate, Items.jimmy_bundle),
            f"Menu -> {Regions.daredevil}": HasAny(Items.daredevil, Items.jimmy_bundle),
            f"Menu -> {Regions.road_work}": HasAny(Items.road_work, Items.jimmy_bundle),
            f"Menu -> {Regions.alternative_medicine}": HasAny(Items.alternative_medicine, Items.jimmy_bundle),
            f"Menu -> {Regions.one_step_at_a_time}": HasAny(Items.one_step_at_a_time, Items.jimmy_bundle),

            f"Menu -> {Regions.avoid_a_roid}": HasAny(Items.avoid_a_roid, Items.mona_bundle),
            f"Menu -> {Regions.foul_balls}": HasAny(Items.foul_balls, Items.mona_bundle),
            f"Menu -> {Regions.balancing_act}": HasAny(Items.balancing_act, Items.mona_bundle),
            f"Menu -> {Regions.happy_birthday}": HasAny(Items.happy_birthday, Items.mona_bundle),
            f"Menu -> {Regions.fancy_footwork}": HasAny(Items.fancy_footwork, Items.mona_bundle),
            f"Menu -> {Regions.doggy_door}": HasAny(Items.doggy_door, Items.mona_bundle),
            f"Menu -> {Regions.hard_pressed}": HasAny(Items.hard_pressed, Items.mona_bundle),
            f"Menu -> {Regions.cat_walk}": HasAny(Items.cat_walk, Items.mona_bundle),
            f"Menu -> {Regions.on_a_roll}": HasAny(Items.on_a_roll, Items.mona_bundle),
            f"Menu -> {Regions.foiled_again}": HasAny(Items.foiled_again, Items.mona_bundle),
            f"Menu -> {Regions.magnafire}": HasAny(Items.magnafire, Items.mona_bundle),
            f"Menu -> {Regions.practical_joker}": HasAny(Items.practical_joker, Items.mona_bundle),
            f"Menu -> {Regions.outta_my_way}": HasAny(Items.outta_my_way, Items.mona_bundle),
            f"Menu -> {Regions.sew_easy}": HasAny(Items.sew_easy, Items.mona_bundle),
            f"Menu -> {Regions.and_the_winner_is}": HasAny(Items.and_the_winner_is, Items.mona_bundle),
            f"Menu -> {Regions.sync_or_sink}": HasAny(Items.sync_or_sink, Items.mona_bundle),
            f"Menu -> {Regions.busted}": HasAny(Items.busted, Items.mona_bundle),
            f"Menu -> {Regions.barrel_roll}": HasAny(Items.barrel_roll, Items.mona_bundle),
            f"Menu -> {Regions.force_feeding}": HasAny(Items.force_feeding, Items.mona_bundle),
            f"Menu -> {Regions.company_picnic}": HasAny(Items.company_picnic, Items.mona_bundle),
            f"Menu -> {Regions.red_delicious}": HasAny(Items.red_delicious, Items.mona_bundle),
            f"Menu -> {Regions.coffee_jitters}": HasAny(Items.coffee_jitters, Items.mona_bundle),
            f"Menu -> {Regions.assembly_flyin}": HasAny(Items.assembly_flyin, Items.mona_bundle),
            f"Menu -> {Regions.welcome_wagon}": HasAny(Items.welcome_wagon, Items.mona_bundle),
            f"Menu -> {Regions.skyway_highway}": HasAny(Items.skyway_highway, Items.mona_bundle),

            f"Menu -> {Regions.bubblegum_blues}": HasAny(Items.bubblegum_blues, Items.kat_ana_bundle),
            f"Menu -> {Regions.big_drip}": HasAny(Items.big_drip, Items.kat_ana_bundle),
            f"Menu -> {Regions.rocky_reunion}": HasAny(Items.rocky_reunion, Items.kat_ana_bundle),
            f"Menu -> {Regions.vicious_veggies}": HasAny(Items.vicious_veggies, Items.kat_ana_bundle),
            f"Menu -> {Regions.nuts}": HasAny(Items.nuts, Items.kat_ana_bundle),
            f"Menu -> {Regions.the_wave}": HasAny(Items.the_wave, Items.kat_ana_bundle),
            f"Menu -> {Regions.contact_lens_solution}": HasAny(Items.contact_lens_solution, Items.kat_ana_bundle),
            f"Menu -> {Regions.going_postal}": HasAny(Items.going_postal, Items.kat_ana_bundle),
            f"Menu -> {Regions.launchpad}": HasAny(Items.launchpad, Items.kat_ana_bundle),
            f"Menu -> {Regions.crazy_crush}": HasAny(Items.crazy_crush, Items.kat_ana_bundle),
            f"Menu -> {Regions.falling_asheep}": HasAny(Items.falling_asheep, Items.kat_ana_bundle),
            f"Menu -> {Regions.stalled_out}": HasAny(Items.stalled_out, Items.kat_ana_bundle),
            f"Menu -> {Regions.thar_he_blows}": HasAny(Items.thar_he_blows, Items.kat_ana_bundle),
            f"Menu -> {Regions.mixed_grill}": HasAny(Items.mixed_grill, Items.kat_ana_bundle),
            f"Menu -> {Regions.survival_of_the_quickest}": HasAny(Items.survival_of_the_quickest, Items.kat_ana_bundle),
            f"Menu -> {Regions.weird_science}": HasAny(Items.weird_science, Items.kat_ana_bundle),
            f"Menu -> {Regions.slap_jack}": HasAny(Items.slap_jack, Items.kat_ana_bundle),
            f"Menu -> {Regions.crazy_straw}": HasAny(Items.crazy_straw, Items.kat_ana_bundle),
            f"Menu -> {Regions.beauty_school}": HasAny(Items.beauty_school, Items.kat_ana_bundle),
            f"Menu -> {Regions.track_star}": HasAny(Items.track_star, Items.kat_ana_bundle),
            f"Menu -> {Regions.nose_dive}": HasAny(Items.nose_dive, Items.kat_ana_bundle),

            f"Menu -> {Regions.shoot_the_fruit}": HasAny(Items.shoot_the_fruit, Items.dribble_bundle),
            f"Menu -> {Regions.d_i_y}": HasAny(Items.d_i_y, Items.dribble_bundle),
            f"Menu -> {Regions.key_ring}": HasAny(Items.key_ring, Items.dribble_bundle),
            f"Menu -> {Regions.county_fair}": HasAny(Items.county_fair, Items.dribble_bundle),
            f"Menu -> {Regions.eating_contest}": HasAny(Items.eating_contest, Items.dribble_bundle),
            f"Menu -> {Regions.spinsecticide}": HasAny(Items.spinsecticide, Items.dribble_bundle),
            f"Menu -> {Regions.i_hate_bananas}": HasAny(Items.i_hate_bananas, Items.dribble_bundle),
            f"Menu -> {Regions.handy_man}": HasAny(Items.handy_man, Items.dribble_bundle),
            f"Menu -> {Regions.homecoming_king}": HasAny(Items.homecoming_king, Items.dribble_bundle),
            f"Menu -> {Regions.wheel_of_whack}": HasAny(Items.wheel_of_whack, Items.dribble_bundle),
            f"Menu -> {Regions.five_second_rule}": HasAny(Items.five_second_rule, Items.dribble_bundle),
            f"Menu -> {Regions.oral_hijinks}": HasAny(Items.oral_hijinks, Items.dribble_bundle),
            f"Menu -> {Regions.beat_down}": HasAny(Items.beat_down, Items.dribble_bundle),
            f"Menu -> {Regions.picky_eater}": HasAny(Items.picky_eater, Items.dribble_bundle),
            f"Menu -> {Regions.gyroid_jumble}": HasAny(Items.gyroid_jumble, Items.dribble_bundle),
            f"Menu -> {Regions.last_piece}": HasAny(Items.last_piece, Items.dribble_bundle),
            f"Menu -> {Regions.heavy_lifting}": HasAny(Items.heavy_lifting, Items.dribble_bundle),
            f"Menu -> {Regions.home_haircut}": HasAny(Items.home_haircut, Items.dribble_bundle),
            f"Menu -> {Regions.tooth_trouble}": HasAny(Items.tooth_trouble, Items.dribble_bundle),
            f"Menu -> {Regions.picture_perfect}": HasAny(Items.picture_perfect, Items.dribble_bundle),
            f"Menu -> {Regions.laser_lineup}": HasAny(Items.laser_lineup, Items.dribble_bundle),
            f"Menu -> {Regions.flip_out}": HasAny(Items.flip_out, Items.dribble_bundle),
            f"Menu -> {Regions.basic_training}": HasAny(Items.basic_training, Items.dribble_bundle),

            f"Menu -> {Regions.cutting_it_close}": HasAny(Items.cutting_it_close, Items.wariowatch_bundle),
            f"Menu -> {Regions.kit_tease}": HasAny(Items.kit_tease, Items.wariowatch_bundle),
            f"Menu -> {Regions.rays_the_devil}": HasAny(Items.rays_the_devil, Items.wariowatch_bundle),
            f"Menu -> {Regions.iron_stomach}": HasAny(Items.iron_stomach, Items.wariowatch_bundle),
            f"Menu -> {Regions.wipeout}": HasAny(Items.wipeout, Items.wariowatch_bundle),
            f"Menu -> {Regions.step_on_it}": HasAny(Items.step_on_it, Items.wariowatch_bundle),
            f"Menu -> {Regions.off_the_wall}": HasAny(Items.off_the_wall, Items.wariowatch_bundle),
            f"Menu -> {Regions.rain_of_terror}": HasAny(Items.rain_of_terror, Items.wariowatch_bundle),
            f"Menu -> {Regions.alien_abduction}": HasAny(Items.alien_abduction, Items.wariowatch_bundle),
            f"Menu -> {Regions.wrecking_all}": HasAny(Items.wrecking_all, Items.wariowatch_bundle),
            f"Menu -> {Regions.micro_golf}": HasAny(Items.micro_golf, Items.wariowatch_bundle),
            f"Menu -> {Regions.nice_catch}": HasAny(Items.nice_catch, Items.wariowatch_bundle),
            f"Menu -> {Regions.opposites_attract}": HasAny(Items.opposites_attract, Items.wariowatch_bundle),
            f"Menu -> {Regions.nuts_and_bolts}": HasAny(Items.nuts_and_bolts, Items.wariowatch_bundle),
            f"Menu -> {Regions.roughing_it}": HasAny(Items.roughing_it, Items.wariowatch_bundle),
            f"Menu -> {Regions.pumping_iron}": HasAny(Items.pumping_iron, Items.wariowatch_bundle),
            f"Menu -> {Regions.party_favor}": HasAny(Items.party_favor, Items.wariowatch_bundle),
            f"Menu -> {Regions.paper_trail}": HasAny(Items.paper_trail, Items.wariowatch_bundle),
            f"Menu -> {Regions.instant_replay}": HasAny(Items.instant_replay, Items.wariowatch_bundle),
            f"Menu -> {Regions.cheeky_monkey}": HasAny(Items.cheeky_monkey, Items.wariowatch_bundle),
            f"Menu -> {Regions.shave_the_world}": HasAny(Items.shave_the_world, Items.wariowatch_bundle),
            f"Menu -> {Regions.chain_letter}": HasAny(Items.chain_letter, Items.wariowatch_bundle),
            f"Menu -> {Regions.dear_john_letter}": HasAny(Items.dear_john_letter, Items.wariowatch_bundle),
            f"Menu -> {Regions.boing}": HasAny(Items.boing, Items.wariowatch_bundle),

            f"Menu -> {Regions.tennis}": HasAny(Items.tennis, Items.nine_volt_bundle),
            f"Menu -> {Regions.metroid_morph_ball}": HasAny(Items.metroid_morph_ball, Items.nine_volt_bundle),
            f"Menu -> {Regions.super_mario_bros_3_lift}": HasAny(Items.super_mario_bros_3_lift, Items.nine_volt_bundle),
            f"Menu -> {Regions.wrecking_crew}": HasAny(Items.wrecking_crew, Items.nine_volt_bundle),
            f"Menu -> {Regions.pinball}": HasAny(Items.pinball, Items.nine_volt_bundle),
            f"Menu -> {Regions.golf}": HasAny(Items.golf, Items.nine_volt_bundle),
            f"Menu -> {Regions.mario_brothers}": HasAny(Items.mario_brothers, Items.nine_volt_bundle),
            f"Menu -> {Regions.excitebike}": HasAny(Items.excitebike, Items.nine_volt_bundle),
            f"Menu -> {Regions.clu_clu_land}": HasAny(Items.clu_clu_land, Items.nine_volt_bundle),
            f"Menu -> {Regions.donkey_kong_jr}": HasAny(Items.donkey_kong_jr, Items.nine_volt_bundle),
            f"Menu -> {Regions.baseball}": HasAny(Items.baseball, Items.nine_volt_bundle),
            f"Menu -> {Regions.ice_climber}": HasAny(Items.ice_climber, Items.nine_volt_bundle),
            f"Menu -> {Regions.balloon_fight}": HasAny(Items.balloon_fight, Items.nine_volt_bundle),
            f"Menu -> {Regions.mach_rider}": HasAny(Items.mach_rider, Items.nine_volt_bundle),
            f"Menu -> {Regions.kid_icarus}": HasAny(Items.kid_icarus, Items.nine_volt_bundle),
            f"Menu -> {Regions.duck_hunt}": HasAny(Items.duck_hunt, Items.nine_volt_bundle),
            f"Menu -> {Regions.the_legend_of_zelda}": HasAny(Items.the_legend_of_zelda, Items.nine_volt_bundle),
            f"Menu -> {Regions.donkey_kong_3}": HasAny(Items.donkey_kong_3, Items.nine_volt_bundle),
            f"Menu -> {Regions.nes_open_tournament_golf}": HasAny(Items.nes_open_tournament_golf, Items.nine_volt_bundle),
            f"Menu -> {Regions.ice_hockey}": HasAny(Items.ice_hockey, Items.nine_volt_bundle),
            f"Menu -> {Regions.metroid_samus}": HasAny(Items.metroid_samus, Items.nine_volt_bundle),
            f"Menu -> {Regions.super_mario_bros_3}": HasAny(Items.super_mario_bros_3, Items.nine_volt_bundle),
            f"Menu -> {Regions.super_mario_bros}": HasAny(Items.super_mario_bros, Items.nine_volt_bundle),

            f"Menu -> {Regions.whats_the_point}": HasAny(Items.whats_the_point, Items.fronk_bundle),
            f"Menu -> {Regions.oopsy_daisy}": HasAny(Items.oopsy_daisy, Items.fronk_bundle),
            f"Menu -> {Regions.hop_to_the_top}": HasAny(Items.hop_to_the_top, Items.fronk_bundle),
            f"Menu -> {Regions.rock_and_a_hot_place}": HasAny(Items.rock_and_a_hot_place, Items.fronk_bundle),
            f"Menu -> {Regions.dirty_darts}": HasAny(Items.dirty_darts, Items.fronk_bundle),
            f"Menu -> {Regions.snake_snarl}": HasAny(Items.snake_snarl, Items.fronk_bundle),
            f"Menu -> {Regions.feed_on_fronk}": HasAny(Items.feed_on_fronk, Items.fronk_bundle),
            f"Menu -> {Regions.peak_a_boo_boo}": HasAny(Items.peak_a_boo_boo, Items.fronk_bundle),
            f"Menu -> {Regions.fronk_fishing}": HasAny(Items.fronk_fishing, Items.fronk_bundle),
        }

    def set_rules(self) -> None:
        for entrance_name, rule in self.connection_rules.items():
            try:
                entrance = self.world.get_entrance(entrance_name)
                self.world.set_rule(entrance, rule)
            except KeyError:
                continue

        self.world.set_completion_rule(Has(Items.victory))
