from .constants import *
from .enums import Regions, Items

game_data = {
    Regions.wario: 0x00,
    Regions.mona: 0x28,
    Regions.jimmy: 0x08,
    Regions.kat_ana: 0x20,
    Regions.dribble: 0x18,
    Regions.crygor: 0x30,
    Regions.orbulon: 0x38,
    Regions.nine_volt: 0x10,
    Regions.wario_man: 0x40,
    Regions.jimmy_folks: 0x58,
    Regions.wariowatch: 0x50,
    Regions.wariowatch_2: 0x78,
    Regions.skyscraper: 0x60,
    Regions.tower: 0x70,
    Regions.mansion: 0x68,
}

score_only_games = {
    Regions.wariowatch_2,
    Regions.skyscraper,
    Regions.tower,
    Regions.mansion,
}


game_scores = {
    Regions.wario:          [],
    Regions.mona:           [4, 8, 12, 16, 20],
    Regions.jimmy:          [4, 8, 12, 16, 20],
    Regions.kat_ana:        [4, 8, 12, 16, 20],
    Regions.dribble:        [4, 8, 12, 16, 20],
    Regions.crygor:         [4, 8, 12, 16, 20],
    Regions.orbulon:        [4, 8, 12, 16, 20],
    Regions.nine_volt:      [4, 8, 12, 16, 20],
    Regions.wario_man:      [8, 12, 16, 20, 25],
    Regions.jimmy_folks:    [4, 8, 12, 16, 20],
    Regions.wariowatch:     [3, 6, 12, 15, 18],
    Regions.wariowatch_2:   [1, 2, 3, 5, 8],
    Regions.skyscraper:     [5, 10, 15, 20, 25],
    Regions.tower:          [2, 4, 6, 8, 10],
    Regions.mansion:        [2, 4, 6, 8, 10],
}

microgame_data = {
    Regions.tiptoe_titan: 0x039,
    Regions.rain_of_riches: 0x0F6,
    Regions.power_line_pigeons: 0x041,
    Regions.burying_the_hatchet: 0x0D2,
    Regions.crash_prize: 0x07E,
    Regions.hot_rod: 0x06B,
    Regions.rock_it: 0x071,
    Regions.ping_pong_panic: 0x0FB,
    Regions.catch_of_the_day: 0x06D,
    Regions.no_zone: 0x13B,
    Regions.alignment: 0x02B,
    Regions.swamp_swing: 0x121,
    Regions.drywall_dodge: 0x0A8,
    Regions.super_wario: 0x140,
    Regions.cyclone_kick: 0x11D,
    Regions.wario_weigh_in: 0x043,
    Regions.going_steady: 0x157,
    Regions.inch_worm: 0x0B8,
    Regions.soda_jerk: 0x13A,
    Regions.robotomy: 0x030,
    Regions.wee_wario_blast: 0x022,
    Regions.fragile: 0x13F,
    Regions.strange_ritual: 0x11A,
    Regions.wario_hockey: 0x096,
    Regions.wario_and_the_beanstalk: 0x0E1,
    Regions.stay_in_school: 0x06C,
    Regions.high_speed_chase: 0x169,
    Regions.volt_bolt: 0x0F9,
    Regions.wario_mambo: 0x0D5,
    Regions.pipe_puzzle: 0x045,
    Regions.air_passage: 0x01D,
    Regions.tapped_out: 0x146,
    Regions.dire_plates: 0x120,
    Regions.deadly_ditty: 0x0F1,
    Regions.alphabet_soup: 0x0A3,
    Regions.manual_labor: 0x080,
    Regions.fine_tune: 0x103,
    Regions.green_thumb: 0x08C,
    Regions.wedgies: 0x0FC,
    Regions.boomerang: 0x015,
    Regions.fill_in_the_blanks: 0x168,
    Regions.peak_peek: 0x0CD,
    Regions.connect_the_dots: 0x0C3,
    Regions.rocket_rotary: 0x0A7,
    Regions.sleight_of_hand: 0x033,
    Regions.guitar_solo: 0x08A,
    Regions.produce_pick: 0x12D,
    Regions.about_face: 0x0C6,
    Regions.safecracker: 0x00C,
    Regions.high_card_draw: 0x095,
    Regions.toaster_jam: 0x14F,
    Regions.crossing_guard: 0x101,
    Regions.hats_off: 0x056,
    Regions.tiltillation: 0x04B,
    Regions.crescent_roll: 0x152,
    Regions.power_outage: 0x021,
    Regions.mooo_ve_it: 0x00D,
    Regions.gravi_key: 0x0B2,
    Regions.half_full: 0x163,
    Regions.cliff_hanger: 0x02D,
    Regions.shake_down: 0x100,
    Regions.heartwrench: 0x038,
    Regions.trash_day: 0x050,
    Regions.half_empty: 0x07D,
    Regions.spout_off: 0x037,
    Regions.aromatherapy: 0x0B0,
    Regions.skid_road: 0x133,
    Regions.balloonatic: 0x078,
    Regions.spitfall: 0x16F,
    Regions.what_goes_in: 0x044,
    Regions.open_and_shut_case: 0x079,
    Regions.shower_power: 0x13C,
    Regions.stumblebot: 0x147,
    Regions.down_in_the_dumps: 0x04F,
    Regions.feel_the_burn: 0x09D,
    Regions.night_and_day: 0x03E,
    Regions.slam_dunk: 0x132,
    Regions.dishpan_hands: 0x162,
    Regions.net_profits: 0x0A1,
    Regions.focus_pocus: 0x148,
    Regions.beware_of_dog: 0x02A,
    Regions.circular_logic: 0x035,
    Regions.h2_whoa: 0x165,
    Regions.twist_and_sprout: 0x06E,
    Regions.bacon_patron: 0x063,
    Regions.make_way_for_martian: 0x167,
    Regions.stab_in_the_dark: 0x027,
    Regions.self_defense: 0x0EE,
    Regions.bright_idea: 0x0B6,
    Regions.dig_this: 0x158,
    Regions.daily_grind: 0x010,
    Regions.ice_queen: 0x09E,
    Regions.save_our_raft: 0x0BC,
    Regions.fashion_plate: 0x093,
    Regions.daredevil: 0x03D,
    Regions.road_work: 0x11B,
    Regions.alternative_medicine: 0x12A,
    Regions.one_step_at_a_time: 0x104,
    Regions.avoid_a_roid: 0x024,
    Regions.foul_balls: 0x046,
    Regions.balancing_act: 0x006,
    Regions.happy_birthday: 0x0D0,
    Regions.fancy_footwork: 0x139,
    Regions.doggy_door: 0x0DD,
    Regions.hard_pressed: 0x0A4,
    Regions.cat_walk: 0x026,
    Regions.on_a_roll: 0x0D6,
    Regions.foiled_again: 0x16A,
    Regions.magnafire: 0x0B5,
    Regions.practical_joker: 0x156,
    Regions.outta_my_way: 0x000,
    Regions.sew_easy: 0x128,
    Regions.and_the_winner_is: 0x0BF,
    Regions.sync_or_sink: 0x145,
    Regions.busted: 0x13D,
    Regions.barrel_roll: 0x0A5,
    Regions.force_feeding: 0x0CE,
    Regions.company_picnic: 0x160,
    Regions.red_delicious: 0x005,
    Regions.coffee_jitters: 0x031,
    Regions.assembly_flyin: 0x034,
    Regions.welcome_wagon: 0x04A,
    Regions.skyway_highway: 0x094,
    Regions.bubblegum_blues: 0x15A,
    Regions.big_drip: 0x141,
    Regions.rocky_reunion: 0x122,
    Regions.vicious_veggies: 0x118,
    Regions.nuts: 0x0B1,
    Regions.the_wave: 0x166,
    Regions.contact_lens_solution: 0x036,
    Regions.going_postal: 0x0FE,
    Regions.launchpad: 0x16E,
    Regions.crazy_crush: 0x01B,
    Regions.falling_asheep: 0x12B,
    Regions.stalled_out: 0x150,
    Regions.thar_he_blows: 0x008,
    Regions.mixed_grill: 0x00E,
    Regions.survival_of_the_quickest: 0x052,
    Regions.weird_science: 0x00F,
    Regions.slap_jack: 0x081,
    Regions.crazy_straw: 0x142,
    Regions.beauty_school: 0x0DE,
    Regions.track_star: 0x017,
    Regions.nose_dive: 0x091,
    Regions.shoot_the_fruit: 0x001,
    Regions.d_i_y: 0x0B4,
    Regions.key_ring: 0x11F,
    Regions.county_fair: 0x0AF,
    Regions.eating_contest: 0x164,
    Regions.spinsecticide: 0x0A6,
    Regions.i_hate_bananas: 0x00A,
    Regions.handy_man: 0x03A,
    Regions.homecoming_king: 0x070,
    Regions.wheel_of_whack: 0x0CB,
    Regions.five_second_rule: 0x004,
    Regions.oral_hijinks: 0x153,
    Regions.beat_down: 0x04C,
    Regions.picky_eater: 0x119,
    Regions.gyroid_jumble: 0x092,
    Regions.last_piece: 0x0F7,
    Regions.heavy_lifting: 0x07C,
    Regions.home_haircut: 0x002,
    Regions.tooth_trouble: 0x042,
    Regions.picture_perfect: 0x12F,
    Regions.laser_lineup: 0x08D,
    Regions.flip_out: 0x072,
    Regions.basic_training: 0x155,
    Regions.cutting_it_close: 0x011,
    Regions.kit_tease: 0x025,
    Regions.rays_the_devil: 0x0BB,
    Regions.iron_stomach: 0x06F,
    Regions.wipeout: 0x16B,
    Regions.step_on_it: 0x131,
    Regions.off_the_wall: 0x08E,
    Regions.rain_of_terror: 0x15B,
    Regions.alien_abduction: 0x082,
    Regions.wrecking_all: 0x126,
    Regions.micro_golf: 0x0DF,
    Regions.nice_catch: 0x007,
    Regions.opposites_attract: 0x0BD,
    Regions.nuts_and_bolts: 0x014,
    Regions.roughing_it: 0x0C1,
    Regions.pumping_iron: 0x0CF,
    Regions.party_favor: 0x0DB,
    Regions.paper_trail: 0x151,
    Regions.instant_replay: 0x15D,
    Regions.cheeky_monkey: 0x09C,
    Regions.shave_the_world: 0x051,
    Regions.chain_letter: 0x159,
    Regions.dear_john_letter: 0x161,
    Regions.boing: 0x00B,
    Regions.tennis: 0x149,
    Regions.metroid_morph_ball: 0x0C4,
    Regions.super_mario_bros_3_lift: 0x134,
    Regions.wrecking_crew: 0x16D,
    Regions.pinball: 0x0FA,
    Regions.golf: 0x089,
    Regions.mario_brothers: 0x0C0,
    Regions.excitebike: 0x053,
    Regions.clu_clu_land: 0x02F,
    Regions.donkey_kong_jr: 0x049,
    Regions.baseball: 0x0C5,
    Regions.ice_climber: 0x09F,
    Regions.balloon_fight: 0x009,
    Regions.mach_rider: 0x0BA,
    Regions.kid_icarus: 0x0DC,
    Regions.duck_hunt: 0x04E,
    Regions.the_legend_of_zelda: 0x172,
    Regions.donkey_kong_3: 0x048,
    Regions.nes_open_tournament_golf: 0x0D7,
    Regions.ice_hockey: 0x0A0,
    Regions.metroid_samus: 0x143,
    Regions.super_mario_bros_3: 0x135,
    Regions.super_mario_bros: 0x136,
    Regions.whats_the_point: 0x02C,
    Regions.oopsy_daisy: 0x03B,
    Regions.hop_to_the_top: 0x15F,
    Regions.rock_and_a_hot_place: 0x03F,
    Regions.dirty_darts: 0x03C,
    Regions.snake_snarl: 0x137,
    Regions.feed_on_fronk: 0x047,
    Regions.peak_a_boo_boo: 0x0B3,
    Regions.fronk_fishing: 0x029,
}

reversed_microgame_data = {v: k for k, v in microgame_data.items()}


microgame_crown_data = {
    Regions.tiptoe_titan: 15,
    Regions.rain_of_riches: 15,
    Regions.power_line_pigeons: 10,
    Regions.burying_the_hatchet: 10,
    Regions.crash_prize: 15,
    Regions.hot_rod: 10,
    Regions.rock_it: 10,
    Regions.ping_pong_panic: 10,
    Regions.catch_of_the_day: 20,
    Regions.no_zone: 15,
    Regions.alignment: 20,
    Regions.swamp_swing: 15,
    Regions.drywall_dodge: 10,
    Regions.super_wario: 15,
    Regions.cyclone_kick: 20,
    Regions.wario_weigh_in: 15,
    Regions.going_steady: 15,
    Regions.inch_worm: 10,
    Regions.soda_jerk: 10,
    Regions.robotomy: 15,
    Regions.wee_wario_blast: 10,
    Regions.fragile: 10,
    Regions.strange_ritual: 15,
    Regions.wario_hockey: 15,
    Regions.wario_and_the_beanstalk: 20,
    Regions.stay_in_school: 20,
    Regions.high_speed_chase: 15,
    Regions.volt_bolt: 10,
    Regions.wario_mambo: 5,
    Regions.pipe_puzzle: 10,
    Regions.air_passage: 10,
    Regions.tapped_out: 15,
    Regions.dire_plates: 10,
    Regions.deadly_ditty: 10,
    Regions.alphabet_soup: 10,
    Regions.manual_labor: 15,
    Regions.fine_tune: 10,
    Regions.green_thumb: 15,
    Regions.wedgies: 20,
    Regions.boomerang: 10,
    Regions.fill_in_the_blanks: 15,
    Regions.peak_peek: 20,
    Regions.connect_the_dots: 15,
    Regions.rocket_rotary: 15,
    Regions.sleight_of_hand: 15,
    Regions.guitar_solo: 15,
    Regions.produce_pick: 20,
    Regions.about_face: 15,
    Regions.safecracker: 15,
    Regions.high_card_draw: 10,
    Regions.toaster_jam: 10,
    Regions.crossing_guard: 5,
    Regions.hats_off: 15,
    Regions.tiltillation: 10,
    Regions.crescent_roll: 15,
    Regions.power_outage: 20,
    Regions.mooo_ve_it: 10,
    Regions.gravi_key: 10,
    Regions.half_full: 10,
    Regions.cliff_hanger: 15,
    Regions.shake_down: 15,
    Regions.heartwrench: 10,
    Regions.trash_day: 15,
    Regions.half_empty: 10,
    Regions.spout_off: 10,
    Regions.aromatherapy: 10,
    Regions.skid_road: 10,
    Regions.balloonatic: 15,
    Regions.spitfall: 10,
    Regions.what_goes_in: 15,
    Regions.open_and_shut_case: 15,
    Regions.shower_power: 10,
    Regions.stumblebot: 5,
    Regions.down_in_the_dumps: 10,
    Regions.feel_the_burn: 10,
    Regions.night_and_day: 10,
    Regions.slam_dunk: 10,
    Regions.dishpan_hands: 10,
    Regions.net_profits: 10,
    Regions.focus_pocus: 10,
    Regions.beware_of_dog: 10,
    Regions.circular_logic: 15,
    Regions.h2_whoa: 15,
    Regions.twist_and_sprout: 10,
    Regions.bacon_patron: 20,
    Regions.make_way_for_martian: 15,
    Regions.stab_in_the_dark: 15,
    Regions.self_defense: 10,
    Regions.bright_idea: 20,
    Regions.dig_this: 15,
    Regions.daily_grind: 15,
    Regions.ice_queen: 15,
    Regions.save_our_raft: 15,
    Regions.fashion_plate: 20,
    Regions.daredevil: 10,
    Regions.road_work: 10,
    Regions.alternative_medicine: 10,
    Regions.one_step_at_a_time: 5,
    Regions.avoid_a_roid: 10,
    Regions.foul_balls: 15,
    Regions.balancing_act: 10,
    Regions.happy_birthday: 20,
    Regions.fancy_footwork: 10,
    Regions.doggy_door: 20,
    Regions.hard_pressed: 10,
    Regions.cat_walk: 15,
    Regions.on_a_roll: 10,
    Regions.foiled_again: 20,
    Regions.magnafire: 10,
    Regions.practical_joker: 15,
    Regions.outta_my_way: 10,
    Regions.sew_easy: 10,
    Regions.and_the_winner_is: 15,
    Regions.sync_or_sink: 10,
    Regions.busted: 15,
    Regions.barrel_roll: 20,
    Regions.force_feeding: 15,
    Regions.company_picnic: 10,
    Regions.red_delicious: 10,
    Regions.coffee_jitters: 20,
    Regions.assembly_flyin: 10,
    Regions.welcome_wagon: 10,
    Regions.skyway_highway: 5,
    Regions.bubblegum_blues: 15,
    Regions.big_drip: 20,
    Regions.rocky_reunion: 15,
    Regions.vicious_veggies: 15,
    Regions.nuts: 10,
    Regions.the_wave: 20,
    Regions.contact_lens_solution: 10,
    Regions.going_postal: 20,
    Regions.launchpad: 20,
    Regions.crazy_crush: 15,
    Regions.falling_asheep: 20,
    Regions.stalled_out: 15,
    Regions.thar_he_blows: 20,
    Regions.mixed_grill: 10,
    Regions.survival_of_the_quickest: 10,
    Regions.weird_science: 10,
    Regions.slap_jack: 15,
    Regions.crazy_straw: 10,
    Regions.beauty_school: 15,
    Regions.track_star: 15,
    Regions.nose_dive: 5,
    Regions.shoot_the_fruit: 10,
    Regions.d_i_y: 15,
    Regions.key_ring: 15,
    Regions.county_fair: 10,
    Regions.eating_contest: 15,
    Regions.spinsecticide: 10,
    Regions.i_hate_bananas: 10,
    Regions.handy_man: 15,
    Regions.homecoming_king: 10,
    Regions.wheel_of_whack: 10,
    Regions.five_second_rule: 15,
    Regions.oral_hijinks: 20,
    Regions.beat_down: 15,
    Regions.picky_eater: 15,
    Regions.gyroid_jumble: 15,
    Regions.last_piece: 10,
    Regions.heavy_lifting: 20,
    Regions.home_haircut: 15,
    Regions.tooth_trouble: 10,
    Regions.picture_perfect: 15,
    Regions.laser_lineup: 10,
    Regions.flip_out: 10,
    Regions.basic_training: 5,
    Regions.cutting_it_close: 10,
    Regions.kit_tease: 10,
    Regions.rays_the_devil: 10,
    Regions.iron_stomach: 10,
    Regions.wipeout: 10,
    Regions.step_on_it: 10,
    Regions.off_the_wall: 15,
    Regions.rain_of_terror: 10,
    Regions.alien_abduction: 15,
    Regions.wrecking_all: 15,
    Regions.micro_golf: 10,
    Regions.nice_catch: 5,
    Regions.opposites_attract: 10,
    Regions.nuts_and_bolts: 20,
    Regions.roughing_it: 10,
    Regions.pumping_iron: 20,
    Regions.party_favor: 15,
    Regions.paper_trail: 10,
    Regions.instant_replay: 10,
    Regions.cheeky_monkey: 10,
    Regions.shave_the_world: 10,
    Regions.chain_letter: 10,
    Regions.dear_john_letter: 15,
    Regions.boing: 10,
    Regions.tennis: 10,
    Regions.metroid_morph_ball: 10,
    Regions.super_mario_bros_3_lift: 10,
    Regions.wrecking_crew: 10,
    Regions.pinball: 15,
    Regions.golf: 10,
    Regions.mario_brothers: 10,
    Regions.excitebike: 15,
    Regions.clu_clu_land: 15,
    Regions.donkey_kong_jr: 15,
    Regions.baseball: 20,
    Regions.ice_climber: 15,
    Regions.balloon_fight: 10,
    Regions.mach_rider: 10,
    Regions.kid_icarus: 10,
    Regions.duck_hunt: 10,
    Regions.the_legend_of_zelda: 10,
    Regions.donkey_kong_3: 20,
    Regions.nes_open_tournament_golf: 10,
    Regions.ice_hockey: 10,
    Regions.metroid_samus: 15,
    Regions.super_mario_bros_3: 15,
    Regions.super_mario_bros: 5,
    Regions.whats_the_point: 10,
    Regions.oopsy_daisy: 15,
    Regions.hop_to_the_top: 10,
    Regions.rock_and_a_hot_place: 15,
    Regions.dirty_darts: 10,
    Regions.snake_snarl: 10,
    Regions.feed_on_fronk: 20,
    Regions.peak_a_boo_boo: 20,
    Regions.fronk_fishing: 20,
}


game_groups = {
    Items.wario_man_bundle: [
        Regions.tiptoe_titan.value,
        Regions.rain_of_riches.value,
        Regions.power_line_pigeons.value,
        Regions.burying_the_hatchet.value,
        Regions.crash_prize.value,
        Regions.hot_rod.value,
        Regions.rock_it.value,
        Regions.ping_pong_panic.value,
        Regions.catch_of_the_day.value,
        Regions.no_zone.value,
        Regions.alignment.value,
        Regions.swamp_swing.value,
        Regions.drywall_dodge.value,
        Regions.super_wario.value,
        Regions.cyclone_kick.value,
        Regions.wario_weigh_in.value,
        Regions.going_steady.value,
        Regions.inch_worm.value,
        Regions.soda_jerk.value,
        Regions.robotomy.value,
        Regions.wee_wario_blast.value,
        Regions.fragile.value,
        Regions.strange_ritual.value,
        Regions.wario_hockey.value,
        Regions.wario_and_the_beanstalk.value,
        Regions.stay_in_school.value,
        Regions.high_speed_chase.value,
        Regions.volt_bolt.value,
        Regions.wario_mambo.value,
    ],
    Items.orbulon_bundle: [
        Regions.pipe_puzzle.value,
        Regions.air_passage.value,
        Regions.tapped_out.value,
        Regions.dire_plates.value,
        Regions.deadly_ditty.value,
        Regions.alphabet_soup.value,
        Regions.manual_labor.value,
        Regions.fine_tune.value,
        Regions.green_thumb.value,
        Regions.wedgies.value,
        Regions.boomerang.value,
        Regions.fill_in_the_blanks.value,
        Regions.peak_peek.value,
        Regions.connect_the_dots.value,
        Regions.rocket_rotary.value,
        Regions.sleight_of_hand.value,
        Regions.guitar_solo.value,
        Regions.produce_pick.value,
        Regions.about_face.value,
        Regions.safecracker.value,
        Regions.high_card_draw.value,
        Regions.toaster_jam.value,
        Regions.crossing_guard.value,
    ],
    Items.crygor_bundle: [
        Regions.hats_off.value,
        Regions.tiltillation.value,
        Regions.crescent_roll.value,
        Regions.power_outage.value,
        Regions.mooo_ve_it.value,
        Regions.gravi_key.value,
        Regions.half_full.value,
        Regions.cliff_hanger.value,
        Regions.shake_down.value,
        Regions.heartwrench.value,
        Regions.trash_day.value,
        Regions.half_empty.value,
        Regions.spout_off.value,
        Regions.aromatherapy.value,
        Regions.skid_road.value,
        Regions.balloonatic.value,
        Regions.spitfall.value,
        Regions.what_goes_in.value,
        Regions.open_and_shut_case.value,
        Regions.shower_power.value,
        Regions.stumblebot.value,
    ],
    Items.jimmy_bundle: [
        Regions.down_in_the_dumps.value,
        Regions.feel_the_burn.value,
        Regions.night_and_day.value,
        Regions.slam_dunk.value,
        Regions.dishpan_hands.value,
        Regions.net_profits.value,
        Regions.focus_pocus.value,
        Regions.beware_of_dog.value,
        Regions.circular_logic.value,
        Regions.h2_whoa.value,
        Regions.twist_and_sprout.value,
        Regions.bacon_patron.value,
        Regions.make_way_for_martian.value,
        Regions.stab_in_the_dark.value,
        Regions.self_defense.value,
        Regions.bright_idea.value,
        Regions.dig_this.value,
        Regions.daily_grind.value,
        Regions.ice_queen.value,
        Regions.save_our_raft.value,
        Regions.fashion_plate.value,
        Regions.daredevil.value,
        Regions.road_work.value,
        Regions.alternative_medicine.value,
        Regions.one_step_at_a_time.value,
    ],
    Items.mona_bundle: [
        Regions.avoid_a_roid.value,
        Regions.foul_balls.value,
        Regions.balancing_act.value,
        Regions.happy_birthday.value,
        Regions.fancy_footwork.value,
        Regions.doggy_door.value,
        Regions.hard_pressed.value,
        Regions.cat_walk.value,
        Regions.on_a_roll.value,
        Regions.foiled_again.value,
        Regions.magnafire.value,
        Regions.practical_joker.value,
        Regions.outta_my_way.value,
        Regions.sew_easy.value,
        Regions.and_the_winner_is.value,
        Regions.sync_or_sink.value,
        Regions.busted.value,
        Regions.barrel_roll.value,
        Regions.force_feeding.value,
        Regions.company_picnic.value,
        Regions.red_delicious.value,
        Regions.coffee_jitters.value,
        Regions.assembly_flyin.value,
        Regions.welcome_wagon.value,
        Regions.skyway_highway.value,
    ],
    Items.kat_ana_bundle: [
        Regions.bubblegum_blues.value,
        Regions.big_drip.value,
        Regions.rocky_reunion.value,
        Regions.vicious_veggies.value,
        Regions.nuts.value,
        Regions.the_wave.value,
        Regions.contact_lens_solution.value,
        Regions.going_postal.value,
        Regions.launchpad.value,
        Regions.crazy_crush.value,
        Regions.falling_asheep.value,
        Regions.stalled_out.value,
        Regions.thar_he_blows.value,
        Regions.mixed_grill.value,
        Regions.survival_of_the_quickest.value,
        Regions.weird_science.value,
        Regions.slap_jack.value,
        Regions.crazy_straw.value,
        Regions.beauty_school.value,
        Regions.track_star.value,
        Regions.nose_dive.value,
    ],
    Items.dribble_bundle: [
        Regions.shoot_the_fruit.value,
        Regions.d_i_y.value,
        Regions.key_ring.value,
        Regions.county_fair.value,
        Regions.eating_contest.value,
        Regions.spinsecticide.value,
        Regions.i_hate_bananas.value,
        Regions.handy_man.value,
        Regions.homecoming_king.value,
        Regions.wheel_of_whack.value,
        Regions.five_second_rule.value,
        Regions.oral_hijinks.value,
        Regions.beat_down.value,
        Regions.picky_eater.value,
        Regions.gyroid_jumble.value,
        Regions.last_piece.value,
        Regions.heavy_lifting.value,
        Regions.home_haircut.value,
        Regions.tooth_trouble.value,
        Regions.picture_perfect.value,
        Regions.laser_lineup.value,
        Regions.flip_out.value,
        Regions.basic_training.value,
    ],
    Items.wariowatch_bundle: [
        Regions.cutting_it_close.value,
        Regions.kit_tease.value,
        Regions.rays_the_devil.value,
        Regions.iron_stomach.value,
        Regions.wipeout.value,
        Regions.step_on_it.value,
        Regions.off_the_wall.value,
        Regions.rain_of_terror.value,
        Regions.alien_abduction.value,
        Regions.wrecking_all.value,
        Regions.micro_golf.value,
        Regions.nice_catch.value,
        Regions.opposites_attract.value,
        Regions.nuts_and_bolts.value,
        Regions.roughing_it.value,
        Regions.pumping_iron.value,
        Regions.party_favor.value,
        Regions.paper_trail.value,
        Regions.instant_replay.value,
        Regions.cheeky_monkey.value,
        Regions.shave_the_world.value,
        Regions.chain_letter.value,
        Regions.dear_john_letter.value,
        Regions.boing.value,
    ],
    Items.nine_volt_bundle: [
        Regions.tennis.value,
        Regions.metroid_morph_ball.value,
        Regions.super_mario_bros_3_lift.value,
        Regions.wrecking_crew.value,
        Regions.pinball.value,
        Regions.golf.value,
        Regions.mario_brothers.value,
        Regions.excitebike.value,
        Regions.clu_clu_land.value,
        Regions.donkey_kong_jr.value,
        Regions.baseball.value,
        Regions.ice_climber.value,
        Regions.balloon_fight.value,
        Regions.mach_rider.value,
        Regions.kid_icarus.value,
        Regions.duck_hunt.value,
        Regions.the_legend_of_zelda.value,
        Regions.donkey_kong_3.value,
        Regions.nes_open_tournament_golf.value,
        Regions.ice_hockey.value,
        Regions.metroid_samus.value,
        Regions.super_mario_bros_3.value,
        Regions.super_mario_bros.value,
    ],
    Items.fronk_bundle: [
        Regions.whats_the_point.value,
        Regions.oopsy_daisy.value,
        Regions.hop_to_the_top.value,
        Regions.rock_and_a_hot_place.value,
        Regions.dirty_darts.value,
        Regions.snake_snarl.value,
        Regions.feed_on_fronk.value,
        Regions.peak_a_boo_boo.value,
        Regions.fronk_fishing.value,
    ],
}


microgame_text_data = {
    Regions.tiptoe_titan: 0x03A,
    Regions.rain_of_riches: 0x0EF,
    Regions.power_line_pigeons: 0x042,
    Regions.burying_the_hatchet: 0x0CC,
    Regions.crash_prize: 0x079,
    Regions.hot_rod: 0x06B,
    Regions.rock_it: 0x071,
    Regions.ping_pong_panic: 0x0F4,
    Regions.catch_of_the_day: 0x06D,
    Regions.no_zone: 0x132,
    Regions.alignment: 0x02C,
    Regions.swamp_swing: 0x118,
    Regions.drywall_dodge: 0x0A2,
    Regions.super_wario: 0x137,
    Regions.cyclone_kick: 0x114,
    Regions.wario_weigh_in: 0x044,
    Regions.going_steady: 0x14F,
    Regions.inch_worm: 0x0B2,
    Regions.soda_jerk: 0x131,
    Regions.robotomy: 0x031,
    Regions.wee_wario_blast: 0x023,
    Regions.fragile: 0x136,
    Regions.strange_ritual: 0x112,
    Regions.wario_hockey: 0x090,
    Regions.wario_and_the_beanstalk: 0x0DA,
    Regions.stay_in_school: 0x06C,
    Regions.high_speed_chase: 0x161,
    Regions.volt_bolt: 0x0F2,
    Regions.wario_mambo: 0x0CE,

    Regions.pipe_puzzle: 0x046,
    Regions.air_passage: 0x01E,
    Regions.tapped_out: 0x13D,
    Regions.dire_plates: 0x117,
    Regions.deadly_ditty: 0x0EA,
    Regions.alphabet_soup: 0x09D,
    Regions.manual_labor: 0x07B,
    Regions.fine_tune: 0x0FB,
    Regions.green_thumb: 0x086,
    Regions.wedgies: 0x0F5,
    Regions.boomerang: 0x016,
    Regions.fill_in_the_blanks: 0x160,
    Regions.peak_peek: 0x0C7,
    Regions.connect_the_dots: 0x0BD,
    Regions.rocket_rotary: 0x0A1,
    Regions.sleight_of_hand: 0x034,
    Regions.guitar_solo: 0x085,
    Regions.produce_pick: 0x124,
    Regions.about_face: 0x0C0,
    Regions.safecracker: 0x00C,
    Regions.high_card_draw: 0x08F,
    Regions.toaster_jam: 0x147,
    Regions.crossing_guard: 0x0FA,

    Regions.hats_off: 0x056,
    Regions.tiltillation: 0x04C,
    Regions.crescent_roll: 0x14A,
    Regions.power_outage: 0x022,
    Regions.mooo_ve_it: 0x00D,
    Regions.gravi_key: 0x0AC,
    Regions.half_full: 0x15B,
    Regions.cliff_hanger: 0x02E,
    Regions.shake_down: 0x0F9,
    Regions.heartwrench: 0x039,
    Regions.trash_day: 0x050,
    Regions.half_empty: 0x078,
    Regions.spout_off: 0x038,
    Regions.aromatherapy: 0x0AA,
    Regions.skid_road: 0x12A,
    Regions.balloonatic: 0x074,
    Regions.spitfall: 0x167,
    Regions.what_goes_in: 0x045,
    Regions.open_and_shut_case: 0x075,
    Regions.shower_power: 0x133,
    Regions.stumblebot: 0x13E,

    Regions.down_in_the_dumps: 0x04F,
    Regions.feel_the_burn: 0x097,
    Regions.night_and_day: 0x03F,
    Regions.slam_dunk: 0x129,
    Regions.dishpan_hands: 0x15A,
    Regions.net_profits: 0x09B,
    Regions.focus_pocus: 0x13F,
    Regions.beware_of_dog: 0x02B,
    Regions.circular_logic: 0x036,
    Regions.h2_whoa: 0x15D,
    Regions.twist_and_sprout: 0x06E,
    Regions.bacon_patron: 0x063,
    Regions.make_way_for_martian: 0x15F,
    Regions.stab_in_the_dark: 0x028,
    Regions.self_defense: 0x0E7,
    Regions.bright_idea: 0x0B0,
    Regions.dig_this: 0x150,
    Regions.daily_grind: 0x011,
    Regions.ice_queen: 0x098,
    Regions.save_our_raft: 0x0B6,
    Regions.fashion_plate: 0x08D,
    Regions.daredevil: 0x03E,
    Regions.road_work: 0x113,
    Regions.alternative_medicine: 0x121,
    Regions.one_step_at_a_time: 0x0FC,

    Regions.avoid_a_roid: 0x025,
    Regions.foul_balls: 0x047,
    Regions.balancing_act: 0x006,
    Regions.happy_birthday: 0x0CA,
    Regions.fancy_footwork: 0x130,
    Regions.doggy_door: 0x0D6,
    Regions.hard_pressed: 0x09E,
    Regions.cat_walk: 0x027,
    Regions.on_a_roll: 0x0CF,
    Regions.foiled_again: 0x162,
    Regions.magnafire: 0x0AF,
    Regions.practical_joker: 0x14E,
    Regions.outta_my_way: 0x000,
    Regions.sew_easy: 0x11F,
    Regions.and_the_winner_is: 0x0B9,
    Regions.sync_or_sink: 0x13C,
    Regions.busted: 0x134,
    Regions.barrel_roll: 0x09F,
    Regions.force_feeding: 0x0C8,
    Regions.company_picnic: 0x158,
    Regions.red_delicious: 0x005,
    Regions.coffee_jitters: 0x032,
    Regions.assembly_flyin: 0x035,
    Regions.welcome_wagon: 0x04B,
    Regions.skyway_highway: 0x08E,

    Regions.bubblegum_blues: 0x152,
    Regions.big_drip: 0x138,
    Regions.rocky_reunion: 0x119,
    Regions.vicious_veggies: 0x10F,
    Regions.nuts: 0x0AB,
    Regions.the_wave: 0x15E,
    Regions.contact_lens_solution: 0x037,
    Regions.going_postal: 0x0F7,
    Regions.launchpad: 0x166,
    Regions.crazy_crush: 0x01C,
    Regions.falling_asheep: 0x122,
    Regions.stalled_out: 0x148,
    Regions.thar_he_blows: 0x008,
    Regions.mixed_grill: 0x00E,
    Regions.survival_of_the_quickest: 0x052,
    Regions.weird_science: 0x010,
    Regions.slap_jack: 0x07C,
    Regions.crazy_straw: 0x139,
    Regions.beauty_school: 0x0D7,
    Regions.track_star: 0x018,
    Regions.nose_dive: 0x08B,

    Regions.shoot_the_fruit: 0x001,
    Regions.d_i_y: 0x0AE,
    Regions.key_ring: 0x116,
    Regions.county_fair: 0x0A9,
    Regions.eating_contest: 0x15C,
    Regions.spinsecticide: 0x0A0,
    Regions.i_hate_bananas: 0x00A,
    Regions.handy_man: 0x03B,
    Regions.homecoming_king: 0x070,
    Regions.wheel_of_whack: 0x0C5,
    Regions.five_second_rule: 0x004,
    Regions.oral_hijinks: 0x14B,
    Regions.beat_down: 0x04D,
    Regions.picky_eater: 0x110,
    Regions.gyroid_jumble: 0x08C,
    Regions.last_piece: 0x0F0,
    Regions.heavy_lifting: 0x077,
    Regions.home_haircut: 0x002,
    Regions.tooth_trouble: 0x043,
    Regions.picture_perfect: 0x126,
    Regions.laser_lineup: 0x087,
    Regions.flip_out: 0x072,
    Regions.basic_training: 0x14D,

    Regions.cutting_it_close: 0x012,
    Regions.kit_tease: 0x026,
    Regions.rays_the_devil: 0x0B5,
    Regions.iron_stomach: 0x06F,
    Regions.wipeout: 0x163,
    Regions.step_on_it: 0x128,
    Regions.off_the_wall: 0x088,
    Regions.rain_of_terror: 0x153,
    Regions.alien_abduction: 0x07D,
    Regions.wrecking_all: 0x11D,
    Regions.micro_golf: 0x0D8,
    Regions.nice_catch: 0x007,
    Regions.opposites_attract: 0x0B7,
    Regions.nuts_and_bolts: 0x015,
    Regions.roughing_it: 0x0BB,
    Regions.pumping_iron: 0x0C9,
    Regions.party_favor: 0x0D4,
    Regions.paper_trail: 0x149,
    Regions.instant_replay: 0x155,
    Regions.cheeky_monkey: 0x096,
    Regions.shave_the_world: 0x051,
    Regions.chain_letter: 0x151,
    Regions.dear_john_letter: 0x159,
    Regions.boing: 0x00B,

    Regions.tennis: 0x140,
    Regions.metroid_morph_ball: 0x0BE,
    Regions.super_mario_bros_3_lift: 0x12C,
    Regions.wrecking_crew: 0x165,
    Regions.pinball: 0x0F3,
    Regions.golf: 0x084,
    Regions.mario_brothers: 0x0BA,
    Regions.excitebike: 0x053,
    Regions.clu_clu_land: 0x030,
    Regions.donkey_kong_jr: 0x04A,
    Regions.baseball: 0x0BF,
    Regions.ice_climber: 0x099,
    Regions.balloon_fight: 0x009,
    Regions.mach_rider: 0x0B4,
    Regions.kid_icarus: 0x0D5,
    Regions.duck_hunt: 0x04E,
    Regions.the_legend_of_zelda: 0x16A,
    Regions.donkey_kong_3: 0x049,
    Regions.nes_open_tournament_golf: 0x0D0,
    Regions.ice_hockey: 0x09A,
    Regions.metroid_samus: 0x13A,
    Regions.super_mario_bros_3: 0x12D,
    Regions.super_mario_bros: 0x12B,

    Regions.whats_the_point: 0x02D,
    Regions.oopsy_daisy: 0x03C,
    Regions.hop_to_the_top: 0x157,
    Regions.rock_and_a_hot_place: 0x040,
    Regions.dirty_darts: 0x03D,
    Regions.snake_snarl: 0x12E,
    Regions.feed_on_fronk: 0x048,
    Regions.peak_a_boo_boo: 0x0AD,
    Regions.fronk_fishing: 0x02A,
}